<Workspace Version="1.1.0.2094" X="-1086.04848157397" Y="-286.438208220842" zoom="1.33823125" Name="Element.GetJoinedElements" Description="This will obtain the elements joined to the input element." ID="6c74f082-2bf3-4043-8660-6cf506c31f72" Category="Rhythm.Revit.Elements.Element">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="b9ff6bed-e406-4222-8747-e16f19fb46c6" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1030.9186735177" y="540.084979949187" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from System.Collections.Generic import *
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

#unwrap all elements to use with API
items = UnwrapElement(IN[0])
TransactionManager.Instance.EnsureInTransaction(doc)
#get the joined element ids
typelist = list()
for i in items:
	try:
		typelist.append(JoinGeometryUtils.GetJoinedElements(doc,i))
	except:
		typelist.append(List())

# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable
OUT = typelist</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="8f5fdeb5-f086-4091-bca1-219aec6ddae1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1503.08487439968" y="529.789195597118" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
items = UnwrapElement(IN[0])

elementlist = list()
unmatched = list()
for item in items:
	try: 
		elementlist.append(doc.GetElement(item).ToDSType(True))
	except:
		unmatched.append(item)
OUT = (elementlist, unmatched)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="fdbf085b-7e76-4638-b6d1-52ba2118694e" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="766.560800870552" y="544.593329815008" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="851edec8-2443-4a51-978d-201dbb2033b9" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="639.686512756277" y="535.36203718217" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="9ef691ae-8164-4287-9df5-9843cd08dcd3" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1932.43767216912" y="662.395388107132" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="joinedElements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e4c1a0fe-c504-4585-af0d-8005e8d3f141" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1707.63848269871" y="529.78019494015" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="f1d09ff1-8799-458d-8a57-734eabe66d42" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1233.00698707639" y="541.340077225698" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b007646a-2b27-4d71-a348-cc958d35781a" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Count" x="1235.99600709816" y="678.087743221392" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Count@var[]..[]" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5002b06a-ed50-474d-912a-d4dc30613873" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Chop" x="1765.05255095035" y="642.966757965667" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Chop@var[]..[],int[]" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="b9ff6bed-e406-4222-8747-e16f19fb46c6" start_index="0" end="f1d09ff1-8799-458d-8a57-734eabe66d42" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b9ff6bed-e406-4222-8747-e16f19fb46c6" start_index="0" end="b007646a-2b27-4d71-a348-cc958d35781a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8f5fdeb5-f086-4091-bca1-219aec6ddae1" start_index="0" end="e4c1a0fe-c504-4585-af0d-8005e8d3f141" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fdbf085b-7e76-4638-b6d1-52ba2118694e" start_index="0" end="b9ff6bed-e406-4222-8747-e16f19fb46c6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="851edec8-2443-4a51-978d-201dbb2033b9" start_index="0" end="fdbf085b-7e76-4638-b6d1-52ba2118694e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e4c1a0fe-c504-4585-af0d-8005e8d3f141" start_index="0" end="5002b06a-ed50-474d-912a-d4dc30613873" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f1d09ff1-8799-458d-8a57-734eabe66d42" start_index="0" end="8f5fdeb5-f086-4091-bca1-219aec6ddae1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b007646a-2b27-4d71-a348-cc958d35781a" start_index="0" end="5002b06a-ed50-474d-912a-d4dc30613873" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5002b06a-ed50-474d-912a-d4dc30613873" start_index="0" end="9ef691ae-8164-4287-9df5-9843cd08dcd3" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="5cd784ef-9192-4339-8722-0b2e496edc18" annotationText="borrowed from Andreas Dieckmann's awesome clockwork package :)" left="1493.08487439968" top="452.789195597118" width="142" height="145" fontSize="14" InitialTop="529.789195597118" InitialHeight="98" TextblockHeight="67" backgrouund="#FFC1D676">
      <Models ModelGuid="8f5fdeb5-f086-4091-bca1-219aec6ddae1" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="5.13294605562702" eyeY="113.702747403948" eyeZ="34.4734420071757" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>