<Workspace Version="0.9.0.3067" X="187.576448497454" Y="-189.013297435779" zoom="1.285282768853" Name="Element.OverrideProjectionLineweight" Description="Overrides the line thickness of projection lines" ID="e7f03df3-0006-4ec9-9a48-cf8e6987c137" Category="Rhythm.Revit.Elements.Element.Actions">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="d9b06ad6-7119-4f62-b0a6-e6e795e55d85" type="PythonNodeModels.PythonNode" nickname="Python Script" x="701.114505784281" y="326.467097783126" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>#Created by DPS Design, dpsdesign.org
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

#unwrap all elements to use with API
elements = []
for i in IN[0]:
	elements.append(UnwrapElement(i))

#create graphic overrides properties
gSettings = Autodesk.Revit.DB.OverrideGraphicSettings()

#set Projection Line weight
gSettings.SetProjectionLineWeight(IN[1])

# "Start" the transaction
TransactionManager.Instance.EnsureInTransaction(doc)

#apply lineweight override to elements in an input list
for i in elements:
	id = i.Id
	doc.ActiveView.SetElementOverrides(id, gSettings)

# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable
OUT = IN[0]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.Symbol guid="55c058e1-de83-47f5-b664-7542b3d5cf89" type="Dynamo.Nodes.Symbol" nickname="Input" x="372.920631394389" y="323.775647862526" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="element" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="66373c8f-2a9c-477f-a0aa-3c2387812ff0" type="Dynamo.Nodes.Symbol" nickname="Input" x="601.47447424556" y="378.023175596092" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="number" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="5e43803c-4740-49f8-9993-a1083cc543f6" type="Dynamo.Nodes.Output" nickname="Output" x="832.541976862877" y="323.560452142273" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Element" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.CodeBlockNodeModel guid="3586ec21-769e-4ff8-b36b-e324e3b2cd7b" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="477.482650349986" y="321.370765118938" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="Flatten({item});" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="d9b06ad6-7119-4f62-b0a6-e6e795e55d85" start_index="0" end="5e43803c-4740-49f8-9993-a1083cc543f6" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="55c058e1-de83-47f5-b664-7542b3d5cf89" start_index="0" end="3586ec21-769e-4ff8-b36b-e324e3b2cd7b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="66373c8f-2a9c-477f-a0aa-3c2387812ff0" start_index="0" end="d9b06ad6-7119-4f62-b0a6-e6e795e55d85" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="3586ec21-769e-4ff8-b36b-e324e3b2cd7b" start_index="0" end="d9b06ad6-7119-4f62-b0a6-e6e795e55d85" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>