<Workspace Version="1.0.0.1180" X="-497.305" Y="-77.6575" zoom="1.1575" Name="Space.IsPointInside" Description="This will test if a point falls within a space." ID="e95c9baa-38e7-4143-b0c8-ff0aee1da4ac" Category="Rhythm.Revit.Elements.Space.Query">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="87cf46e1-7cd2-4f5e-a319-bcb59444bfca" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1318.3027444556" y="444" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]" />
    <PythonNodeModels.PythonNode guid="a0f319da-f4df-4885-9483-8cbb2b0a2f09" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1183.1513722278" y="447.361165717801" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

rooms = UnwrapElement(IN[0])
points = [x.ToXyz() for x in IN[1]]
roomlist = list()
for point in points:
	booleans = list()
	for room in rooms:
		try:
			if room.IsPointInSpace(point):
				booleans.append(True)
			else:
				booleans.append(False)
		except:
			booleans.append(False)
	roomlist.append(booleans)
OUT = roomlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="0ed51957-099e-496c-9566-795cdc29a742" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="929.1513722278" y="452" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item1});&#xA;Flatten({item2});" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="980e4e49-468a-4c4c-bc93-30d0a8de22d8" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Output.Clean" x="1455.98704103672" y="444.628509719222" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <ID value="4176dc53-ab69-4804-beb4-e006bece065c" />
      <Name value="Output.Clean" />
      <Description value="This will return a single value or list from one input." />
      <Inputs>
        <Input value="input" />
      </Inputs>
      <Outputs>
        <Output value="result" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="796e865d-cb95-42b2-837b-00bf661ef831" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="756.203023758099" y="454.995680345572" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="space" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="60571e5d-174d-48cf-a2f3-dfe378778300" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="618.838012958963" y="522.382289416847" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//point to test&#xD;&#xA;point : Autodesk.Point" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e60a09e1-f741-4577-949d-d80c70dec754" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1615.81425485961" y="444.628509719222" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="mask" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="87cf46e1-7cd2-4f5e-a319-bcb59444bfca" start_index="0" end="980e4e49-468a-4c4c-bc93-30d0a8de22d8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a0f319da-f4df-4885-9483-8cbb2b0a2f09" start_index="0" end="87cf46e1-7cd2-4f5e-a319-bcb59444bfca" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0ed51957-099e-496c-9566-795cdc29a742" start_index="0" end="a0f319da-f4df-4885-9483-8cbb2b0a2f09" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0ed51957-099e-496c-9566-795cdc29a742" start_index="1" end="a0f319da-f4df-4885-9483-8cbb2b0a2f09" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="980e4e49-468a-4c4c-bc93-30d0a8de22d8" start_index="0" end="e60a09e1-f741-4577-949d-d80c70dec754" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="796e865d-cb95-42b2-837b-00bf661ef831" start_index="0" end="0ed51957-099e-496c-9566-795cdc29a742" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="60571e5d-174d-48cf-a2f3-dfe378778300" start_index="0" end="0ed51957-099e-496c-9566-795cdc29a742" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>