<Workspace Version="1.3.4.6666" X="-362.412609691052" Y="4.74799200430314" zoom="0.867977507649016" ScaleFactor="1" Name="Dimension By References" Description="Creates a new linear dimension from at least two element references." ID="ba8b7d16-46d3-4c93-96c3-df912d9c1f9e" Category="GeniusLoci.Reference">
  <NamespaceResolutionMap>
    <ClassMap partialName="Revit.Application.Document.Current" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.Application.Document" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="2a669606-9a7a-4425-8bba-844586ea7985" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="625.296984744126" y="343.570602974752" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Dynamo Curve&#xD;&#xA;line" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c816ba57-e7da-420c-b311-9276ca0ecb78" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="637.2" y="429.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="References" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="3d3baadf-39dd-4a12-9658-918a39b36c82" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1081.93822781021" y="390.208508946469" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Dimension" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="89172725-ad21-4146-87d9-1b8577d2cbaf" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="233.044004694257" y="525.633509137527" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="View:var[]..[] = Revit.Application.Document.Current.ActiveView" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="d6c00c09-0142-40a3-ba2f-684af71fe8be" type="PythonNodeModels.PythonNode" nickname="DimensionWithReference" x="846.043503552704" y="379.681247504563" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

def tolist(obj1):
    if hasattr(obj1,"__iter__"): return obj1
    else: return [obj1]

lines = tolist(IN[0])
references= IN[1]
view = tolist(UnwrapElement(IN[2]))[0]

elementsRef = ReferenceArray()
for reference in references :
	elementsRef.Append(reference)
	
TransactionManager.Instance.EnsureInTransaction(doc)
for line in lines:
	dim = doc.Create.NewDimension(view, line.ToRevitType(), elementsRef).ToDSType(True)
TransactionManager.Instance.TransactionTaskDone()

OUT=dim</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2a669606-9a7a-4425-8bba-844586ea7985" start_index="0" end="d6c00c09-0142-40a3-ba2f-684af71fe8be" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c816ba57-e7da-420c-b311-9276ca0ecb78" start_index="0" end="d6c00c09-0142-40a3-ba2f-684af71fe8be" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="89172725-ad21-4146-87d9-1b8577d2cbaf" start_index="0" end="d6c00c09-0142-40a3-ba2f-684af71fe8be" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d6c00c09-0142-40a3-ba2f-684af71fe8be" start_index="0" end="3d3baadf-39dd-4a12-9658-918a39b36c82" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>