<Workspace Version="1.3.3.4651" X="50.2136475890208" Y="109.345119970326" zoom="0.70823125" ScaleFactor="1" Name="FilledRegion Color Change" Description="Change the color of a Filled Region to another given color." ID="2ec30df1-245a-4dff-bbed-ea8d65c223e0" Category="GeniusLoci.Graphics">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="dc2fff53-903a-4659-8f4a-97a1fd500347" type="PythonNodeModels.PythonNode" nickname="Python Script" x="308.4" y="300" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Alban de Chasteigner, 2018
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]
	
def ConvertColor(e):
	return Autodesk.Revit.DB.Color(e.Red, e.Green, e.Blue)

filledRegions = tolist(UnwrapElement(IN[0]))
colors = tolist(IN[1])

TransactionManager.Instance.EnsureInTransaction(doc)
for color,filledRegion in zip(colors,filledRegions) :
	(filledRegion.Document.GetElement(filledRegion.GetTypeId())).Color=ConvertColor(color)
TransactionManager.Instance.TransactionTaskDone()

OUT = filledRegions</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5f0a837c-153b-4730-a102-8aac4af57fdf" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="530.8" y="306" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="FilledRegion" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="aef3fac1-5ee9-4513-8b36-b04bf9054f57" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="90.0000000000001" y="283.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="FilledRegion" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="38f9981a-276b-4279-a393-9d4c0031e49f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-74.5875165618869" y="356.441935497302" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//As many colors as FilledRegions&#xD;&#xA;color" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="dc2fff53-903a-4659-8f4a-97a1fd500347" start_index="0" end="5f0a837c-153b-4730-a102-8aac4af57fdf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="aef3fac1-5ee9-4513-8b36-b04bf9054f57" start_index="0" end="dc2fff53-903a-4659-8f4a-97a1fd500347" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="38f9981a-276b-4279-a393-9d4c0031e49f" start_index="0" end="dc2fff53-903a-4659-8f4a-97a1fd500347" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>