<Workspace Version="1.3.3.4651" X="10.05487384273" Y="11.5892416468843" zoom="0.97676875" ScaleFactor="1" Name="Set DWG Export Setup" Description="Sets the DWGExportOptions stored in the ExportDwgSettings." ID="ffe584bd-02ec-4fb2-b18b-1181548f9afc" Category="GeniusLoci.Export">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5a9f76a6-4e81-4bb5-87fc-97dec510526a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="120.8" y="293.349554896142" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="ExportDwgSettings" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="d4e16b53-92fe-48b0-8ecf-948a0a3f3ddf" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="518.8" y="335.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="ExportDwgSettings" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c0f7fef7-72be-4063-8b68-b5339c3a4cd2" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="117.6" y="382.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="DWGExportOptions" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="7f4c5c6a-b954-45bf-a8c4-4743cc3f066c" type="PythonNodeModels.PythonNode" nickname="SetDWGExportOptions" x="321.6" y="326.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Alban de Chasteigner 2018
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

def toList(obj):
    if hasattr(obj, '__iter__'): return obj
    else: return [obj]

settings = toList(UnwrapElement(IN[0]))
DWGExportOptions = toList(UnwrapElement(IN[1]))

TransactionManager.Instance.EnsureInTransaction(doc)
for i in settings:
	option = i.SetDWGExportOptions(DWGExportOptions[0])
TransactionManager.Instance.TransactionTaskDone()
OUT = settings</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="5a9f76a6-4e81-4bb5-87fc-97dec510526a" start_index="0" end="7f4c5c6a-b954-45bf-a8c4-4743cc3f066c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c0f7fef7-72be-4063-8b68-b5339c3a4cd2" start_index="0" end="7f4c5c6a-b954-45bf-a8c4-4743cc3f066c" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7f4c5c6a-b954-45bf-a8c4-4743cc3f066c" start_index="0" end="d4e16b53-92fe-48b0-8ecf-948a0a3f3ddf" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>