<Workspace Version="1.3.3.4651" X="-18.794" Y="57.954" zoom="0.8425" ScaleFactor="1" Name="Unload RevitLinkInstance" Description="Unloads the Revit link provided.&#xD;&#xA;Based on a Einar Raknes's script." ID="878c2430-f417-4d65-88ac-e53f4f67169e" Category="GeniusLoci.Import">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="5bc4d856-f758-4496-9122-fc4081582f68" type="PythonNodeModels.PythonNode" nickname="Unload Link" x="365.6" y="220.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># Code by Einar Raknes, 2017
import clr
# Import List ( ICollection(ElementId) = List[ElementId]() )
clr.AddReference('System')
from System.Collections.Generic import List

# Import Revit API
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *

clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import *

# Import ToDSType(bool) extension method
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument
app = DocumentManager.Instance.CurrentUIApplication.Application

linkInst = UnwrapElement(IN[0])

TransactionManager.Instance.ForceCloseTransaction()

for link in linkInst:
	linkType = doc.GetElement(link.GetTypeId())
	linkType.Unload(None)

OUT=linkInst</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1093a871-0b2d-406e-9044-6329bcd9729f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="144.8" y="220.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="RevitLinkInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="d772ee92-b418-4855-8758-1119be14fdeb" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="548" y="222" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="RevitLinkInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="5bc4d856-f758-4496-9122-fc4081582f68" start_index="0" end="d772ee92-b418-4855-8758-1119be14fdeb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1093a871-0b2d-406e-9044-6329bcd9729f" start_index="0" end="5bc4d856-f758-4496-9122-fc4081582f68" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>