<Workspace Version="1.0.0.1180" X="333.942146153609" Y="282.830830865502" zoom="1.02988563947098" Name="Area.CreateAtUV" Description="create Area from center points at Level" ID="b66df722-1485-402c-adf1-e7234ebc03b1" Category="SteamNodes.Area">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="847d9a09-27e1-4b17-b7b8-2308f62fb311" type="PythonNodeModels.PythonNode" nickname="Python Script" x="492.489662939819" y="28.0734338245269" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <Script>#python nodes in dynamo 1.0
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

uvs =[]
for i in IN[0]:
	uvs.append(UnwrapElement(i))
view=UnwrapElement(IN[1])
roomlist=[]

# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)

for item in uvs:
	a=doc.Create.NewArea(view,item)
	roomlist.append(a)

# End Transaction
TransactionManager.Instance.TransactionTaskDone()

OUT = roomlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="712fe8fb-bf47-4386-bade-3703da1d9fc5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="UV" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="202d4b8b-edc2-4909-a690-4015eaaa2b6a" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="714" y="29" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Area List" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="0ac523a1-dd6a-4930-81d2-4898dda84271" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="205.164154386828" y="-0.138048983698873" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="cef19b3a-7926-4c5f-b882-9cfffce7c906" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="84" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="View" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="847d9a09-27e1-4b17-b7b8-2308f62fb311" start_index="0" end="202d4b8b-edc2-4909-a690-4015eaaa2b6a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="712fe8fb-bf47-4386-bade-3703da1d9fc5" start_index="0" end="0ac523a1-dd6a-4930-81d2-4898dda84271" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0ac523a1-dd6a-4930-81d2-4898dda84271" start_index="0" end="847d9a09-27e1-4b17-b7b8-2308f62fb311" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cef19b3a-7926-4c5f-b882-9cfffce7c906" start_index="0" end="847d9a09-27e1-4b17-b7b8-2308f62fb311" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>