<Workspace Version="1.3.2.2480" X="-451.739864450813" Y="178.103611026003" zoom="1.78359936238281" ScaleFactor="1" Name="bv Place View On Sheet at Point" Description="originally from SteamNodes" ID="eb6f6060-3330-4f6c-b7e1-0628ef900386" Category="Bakery.Revit.Views.Sheet">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e1bd6ba0-e96a-4da9-bac3-015d701f7985" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="571.666666666667" y="20" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="SheetList" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="727fa142-1e5d-4a0d-b899-34b35412e10e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="571.666666666667" y="170" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="ViewsList" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="783aacbe-315c-4a29-b9df-cb146977a9be" type="PythonNodeModels.PythonNode" nickname="Python Script" x="821.666666666667" y="20" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#python nodes in dynamo 1.2
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

sheets = []
for i in IN[0]:
	sheets.append(UnwrapElement(i))
views=[]	
for i in IN[1]:
	views.append(UnwrapElement(i))
points=[]	
for i in IN[2]:
	points.append(UnwrapElement(i).ToXyz())

# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)
viewp=[]
for s,v,p in zip(sheets,views,points):
	a=Viewport.Create(doc, s.Id,v.Id, p)
	viewp.append(a)

# End Transaction
TransactionManager.Instance.TransactionTaskDone()

OUT=viewp</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="2b389e7d-425c-4a70-a4c0-cec16c699e25" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1018.66666666667" y="20" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="ViewportsPlaced" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="53c29c2f-970b-44d9-a423-f1d0cdf153f7" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="571.666666666667" y="320" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="PointsList" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e1bd6ba0-e96a-4da9-bac3-015d701f7985" start_index="0" end="783aacbe-315c-4a29-b9df-cb146977a9be" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="727fa142-1e5d-4a0d-b899-34b35412e10e" start_index="0" end="783aacbe-315c-4a29-b9df-cb146977a9be" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="783aacbe-315c-4a29-b9df-cb146977a9be" start_index="0" end="2b389e7d-425c-4a70-a4c0-cec16c699e25" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="53c29c2f-970b-44d9-a423-f1d0cdf153f7" start_index="0" end="783aacbe-315c-4a29-b9df-cb146977a9be" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>