<Workspace Version="1.2.1.3083" X="-776.301158112156" Y="-167.860682373359" zoom="1.2198072017255" Name="Save To Central with Options" Description="" ID="4bdfacab-a0e5-4aff-83f1-2764c7a90825" Category="Bakery.Revit.Document">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="572f1efc-2e3d-492d-b473-0fb607414d39" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="492" y="472" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Document" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="5354bb2e-a203-4f4a-8afc-0ef3d97274e8" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="888.5" y="532" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e8b1d1d5-7b01-49dd-84c8-74753c44de81" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="888.5" y="640" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="true;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="8d416010-0623-47bb-8fd1-1a4fad2fd258" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1219.46632622217" y="626.241566496603" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

items = IN[0]
overwrite = IN[1]
savecentral = IN[2]
pathin = IN[3]


soptions = SaveAsOptions()
woptions = WorksharingSaveAsOptions()
woptions.OpenWorksetsDefault = AllWorksets
soptions.OverwriteExistingFile = overwrite
woptions.SaveAsCentral = savecentral
soptions.SetWorksharingOptions(woptions)

typelist = list()


for i, (one, two) in enumerate(zip(items, pathin)): 	
		try:
			one.SaveAs(two,soptions)
		except:
			one.Save()
		
OUT = items</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8ab55663-f76f-4ae9-84b4-13566ab25621" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="480" y="698" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="FilePath" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="b2626643-4330-4bab-a7db-dbae8e6f3899" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Output.Clean" x="1413.6510297633" y="596.786666666667" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <ID value="4176dc53-ab69-4804-beb4-e006bece065c" />
      <Name value="Output.Clean" />
      <Description value="This will return a single value or list from one input." />
      <Inputs>
        <Input value="input" />
      </Inputs>
      <Outputs>
        <Output value="result" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="c4819123-88ff-46af-b6fd-8e3a23e2f6b6" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="888.5" y="748" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="6f6394c8-e427-4a78-9e28-cebad79f77c2" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1739.15133531157" y="612.415430267062" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Document" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="9a3c08cf-6493-48e3-aa52-29f1636714fc" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1215.19298788804" y="394.483665144796" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

items = IN[0]
overwrite = IN[1]
savecentral = IN[2]
pathin = IN[3]


soptions = SaveAsOptions()
woptions = WorksharingSaveAsOptions()
swconfig = SimpleWorksetConfiguration.AllWorksets
woptions.OpenWorksetsDefault = swconfig
soptions.OverwriteExistingFile = overwrite
woptions.SaveAsCentral = savecentral
soptions.SetWorksharingOptions(woptions)

typelist = list()


for i, (one, two) in enumerate(zip(items, pathin)): 	
		try:
			one.SaveAs(two,soptions)
		except:
			one.Save()
		
OUT = items</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="572f1efc-2e3d-492d-b473-0fb607414d39" start_index="0" end="5354bb2e-a203-4f4a-8afc-0ef3d97274e8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5354bb2e-a203-4f4a-8afc-0ef3d97274e8" start_index="0" end="9a3c08cf-6493-48e3-aa52-29f1636714fc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e8b1d1d5-7b01-49dd-84c8-74753c44de81" start_index="0" end="9a3c08cf-6493-48e3-aa52-29f1636714fc" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e8b1d1d5-7b01-49dd-84c8-74753c44de81" start_index="0" end="9a3c08cf-6493-48e3-aa52-29f1636714fc" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8ab55663-f76f-4ae9-84b4-13566ab25621" start_index="0" end="c4819123-88ff-46af-b6fd-8e3a23e2f6b6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b2626643-4330-4bab-a7db-dbae8e6f3899" start_index="0" end="6f6394c8-e427-4a78-9e28-cebad79f77c2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c4819123-88ff-46af-b6fd-8e3a23e2f6b6" start_index="0" end="9a3c08cf-6493-48e3-aa52-29f1636714fc" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9a3c08cf-6493-48e3-aa52-29f1636714fc" start_index="0" end="b2626643-4330-4bab-a7db-dbae8e6f3899" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>