<Workspace Version="1.0.0.1180" X="-649.534020768248" Y="176.99728847077" zoom="0.683206694052568" Name="Area.CreateFromPlanCircuit" Description="Place new Areas in Plan Circuit" ID="28a45fb5-f23e-4516-abb8-9cfbdc69489a" Category="SteamNodes.Area">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="c64bff11-480f-4f50-a618-4aba854a179e" type="PythonNodeModels.PythonNode" nickname="Create Areas from UVs" x="1460.49125620211" y="103.446549999445" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <Script>#python nodes in dynamo 1.0
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

uvs =[]
for i in IN[0]:
	uvs.append(UnwrapElement(i))
view=UnwrapElement(IN[1])
roomlist=[]

# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)

for item in uvs:
	a=doc.Create.NewArea(view,item)
	roomlist.append(a)

# End Transaction
TransactionManager.Instance.TransactionTaskDone()

OUT = roomlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="8cab6156-0e58-4b4d-a16c-a6de10232d8c" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1152.49125620211" y="107.659883332778" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="0484440d-6535-4d99-b1fb-acf6c7ae1c8c" type="PythonNodeModels.PythonNode" nickname="Get Plan Circuit" x="928.491256202111" y="103.446549999445" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#python nodes in dynamo 0.9
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument



level=UnwrapElement(IN[0])
#phase=IN[1]
#cir=[]
points=[]
#rooms=UnwrapElement(IN[2])

phases=doc.Phases
# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)

PT =doc.get_PlanTopology(level)
circuits=PT.Circuits
a=circuits.Size
for p in circuits:
	points.append(p.GetPointInside())

				
				
# End Transaction
TransactionManager.Instance.TransactionTaskDone()
OUT =points
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="248f88ab-4ad1-4a02-85b7-5e15ce796bd3" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1712.49125620211" y="103.446549999445" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Areas" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="be97d440-5d60-4ce3-bbaa-1a7022323bec" type="PythonNodeModels.PythonNode" nickname="Python Script" x="-1.50874379788888" y="116.446549999445" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>#Copyright(c) 2015, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com

import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

OUT = doc.ActiveView.ToDSType(True)</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="3dc81774-ca2e-4900-8479-74e238c3ff8c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="500.491256202111" y="103.446549999445" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
faminsts = UnwrapElement(IN[0])
elementlist = list()
for item in faminsts:
	try:	
		elementlist.append(doc.GetElement(item.LevelId).ToDSType(True))
	except:
		try:
			elementlist.append(item.Level.ToDSType(True))
		except:
			try:
				elementlist.append(item.GenLevel.ToDSType(True))
			except:
				elementlist.append(list())
OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="ecaa3f4c-33b7-47c4-a927-ffb710319036" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="192.491256202111" y="107.659883332778" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="c5a6a83a-e062-4196-8849-6d03bf30f7e0" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="724.491256202111" y="107.659883332778" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="a[0];" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="c64bff11-480f-4f50-a618-4aba854a179e" start_index="0" end="248f88ab-4ad1-4a02-85b7-5e15ce796bd3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8cab6156-0e58-4b4d-a16c-a6de10232d8c" start_index="0" end="c64bff11-480f-4f50-a618-4aba854a179e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0484440d-6535-4d99-b1fb-acf6c7ae1c8c" start_index="0" end="8cab6156-0e58-4b4d-a16c-a6de10232d8c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="be97d440-5d60-4ce3-bbaa-1a7022323bec" start_index="0" end="ecaa3f4c-33b7-47c4-a927-ffb710319036" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="be97d440-5d60-4ce3-bbaa-1a7022323bec" start_index="0" end="c64bff11-480f-4f50-a618-4aba854a179e" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3dc81774-ca2e-4900-8479-74e238c3ff8c" start_index="0" end="c5a6a83a-e062-4196-8849-6d03bf30f7e0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ecaa3f4c-33b7-47c4-a927-ffb710319036" start_index="0" end="3dc81774-ca2e-4900-8479-74e238c3ff8c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c5a6a83a-e062-4196-8849-6d03bf30f7e0" start_index="0" end="0484440d-6535-4d99-b1fb-acf6c7ae1c8c" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="c6514915-99a2-44f6-8e38-ec58b4354cf3" text="From SpringNodes" x="12.3468427425244" y="75.7704863902779" />
    <Dynamo.Graph.Notes.NoteModel guid="5ffbe028-5ad4-4e39-8d06-a9e22c613303" text="From Clockwork" x="507.991256202111" y="60.9465499994451" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>