<Workspace Version="1.0.0.1180" X="6" Y="274.715378635908" zoom="1.49548645937813" Name="Tool.CreateAssembly" Description="Create an Assembly for each element" ID="67d7276c-7704-4489-88f2-cc332178b711" Category="SteamNodes.Tool">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="d7bf8105-f5b6-4df2-8bc1-9fb7f5b5ae5b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="479.547619047619" y="0.00250000000000128" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#python nodes in dynamo 1.0
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

elt = []
for i in IN[0]:
	elt.append(UnwrapElement(i).Id)
	
catid=doc.GetElement(elt[0]).Category.Id
	
collection=List[ElementId](elt)


# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)

a=AssemblyInstance.Create(doc,collection,catid)

# End Transaction
TransactionManager.Instance.TransactionTaskDone()

OUT=a</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="902ca7f6-ae12-4eb7-ae8b-c95356961d55" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="39.5476190476187" y="0.00250000000000128" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="List" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5647a1c6-ad72-4368-a399-27e6aabbc07e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="701.547619047619" y="0.00250000000000128" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Assembly Instance(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="34bc2943-7bad-4129-8d35-12525e4b24ba" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="209.547619047619" y="4.21583333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({a});" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d7bf8105-f5b6-4df2-8bc1-9fb7f5b5ae5b" start_index="0" end="5647a1c6-ad72-4368-a399-27e6aabbc07e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="902ca7f6-ae12-4eb7-ae8b-c95356961d55" start_index="0" end="34bc2943-7bad-4129-8d35-12525e4b24ba" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="34bc2943-7bad-4129-8d35-12525e4b24ba" start_index="0" end="d7bf8105-f5b6-4df2-8bc1-9fb7f5b5ae5b" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>