<Workspace Version="1.2.0.2690" X="141" Y="244" zoom="1" Name="Tool.CropViewFromRoomShapeWithOffset" Description="Crop the floor plan view according to the room shape with an offset value." ID="220790b0-45af-499d-af22-369ff413a8d9" Category="SteamNodes.Tool">
  <NamespaceResolutionMap>
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="dbd04a19-6331-4172-a58a-4d60900d694d" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2037.45659123799" y="38.7786552625618" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script>#python nodes in dynamo 1.2
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import Element wrapper extension methods
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

import System
import math
from System import Array
from System.Collections.Generic import *

looplist=[]
vp=[]
rm=[]
for list in IN[0]:
	loop=[]
	for c in list:
		loop.append(UnwrapElement(c).ToRevitType())
	ILoop=List[Curve](loop)
	CL=CurveLoop.Create(ILoop)
	looplist.append(CL)
for i in IN[1]:	
	vp.append(UnwrapElement(i))
for i in IN[3]:	
	rm.append(UnwrapElement(i))
	
RunMe=IN[2]
if RunMe:
	# Start Transaction
	TransactionManager.Instance.EnsureInTransaction(doc)
	for l,v in zip(looplist,vp):
		#assign CurveLoop to the CropBox of the view
		v.CropBoxActive =True
		cropManager = v.GetCropRegionShapeManager()
		if cropManager.IsValidObject and cropManager.IsCropRegionShapeValid(l):					
			cropManager.SetCropShape(l)
		else:
			print 'Not Allowed to manage Crop for ' + v.Name + ' :-(' 
			v.CropBoxActive = False
	# End Transaction
	TransactionManager.Instance.TransactionTaskDone()
	doc.Regenerate()
else:
	OUT = "Run Me set to False"
#Assign your output to the OUT variable.
OUT = IN[1]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="845b1490-b520-4070-8f88-bd969a20fb51" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Explode" x="1542.57970106422" y="230.020255242586" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Explode">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9f7a391c-b18f-4709-8e5e-6d9f9fdd69ca" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="PolyCurve.Offset" x="1255.56461919157" y="226.923199414726" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.PolyCurve.Offset@double,bool">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="00ff97c2-d610-4b34-be1a-cdcef3910f97" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="PolyCurve.ByJoinedCurves" x="979.352786948911" y="232.187600562124" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.PolyCurve.ByJoinedCurves@Autodesk.DesignScript.Geometry.Curve[]">
      <PortInfo index="0" default="False" useLevels="True" level="2" shouldKeepListStructure="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="add69057-4b6f-428f-b7e5-c06b1f628861" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1057.05716013993" y="317.6911654465" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="0;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3eddc29e-10d7-41d3-9444-72093356d984" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.FirstItem" x="783.769981292261" y="229.821156994754" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.FirstItem@var[]..[]">
      <PortInfo index="0" default="False" useLevels="True" level="3" shouldKeepListStructure="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="f58f64d0-7b7f-4edb-be3a-92c507043af8" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="floor plan" x="534.645277005438" y="100.444434677533" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="2db7dcda-49e7-4cc5-8f75-d2debc046937" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Room.FinishBoundary" x="525.52272601633" y="229.570405164652" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Room.FinishBoundary">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="678f910a-4a3d-4824-8b6f-76353ee810b2" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="rooms" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="38879d43-2874-4885-a26d-ab2b83d1b26e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="4" y="111" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="FloorPlanView" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="fdaca84b-4958-4865-bc66-78900f3ec9c4" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="6" y="3" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Room" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="a0ed9a61-4f64-4986-9d70-0ebad4a9e13a" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="2235.45659123799" y="38" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="FloorPlanView" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c9c99a70-1abc-4079-b395-72f5054c8bee" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="29" y="306" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Offset:double=200" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d8b0e1b2-7745-44b4-bd4a-a3fcf38bfec1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="32" y="419" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="RunMe:bool" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="dbd04a19-6331-4172-a58a-4d60900d694d" start_index="0" end="a0ed9a61-4f64-4986-9d70-0ebad4a9e13a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="845b1490-b520-4070-8f88-bd969a20fb51" start_index="0" end="dbd04a19-6331-4172-a58a-4d60900d694d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9f7a391c-b18f-4709-8e5e-6d9f9fdd69ca" start_index="0" end="845b1490-b520-4070-8f88-bd969a20fb51" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="00ff97c2-d610-4b34-be1a-cdcef3910f97" start_index="0" end="9f7a391c-b18f-4709-8e5e-6d9f9fdd69ca" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="add69057-4b6f-428f-b7e5-c06b1f628861" start_index="0" end="9f7a391c-b18f-4709-8e5e-6d9f9fdd69ca" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3eddc29e-10d7-41d3-9444-72093356d984" start_index="0" end="00ff97c2-d610-4b34-be1a-cdcef3910f97" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f58f64d0-7b7f-4edb-be3a-92c507043af8" start_index="0" end="dbd04a19-6331-4172-a58a-4d60900d694d" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2db7dcda-49e7-4cc5-8f75-d2debc046937" start_index="0" end="3eddc29e-10d7-41d3-9444-72093356d984" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="678f910a-4a3d-4824-8b6f-76353ee810b2" start_index="0" end="2db7dcda-49e7-4cc5-8f75-d2debc046937" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="678f910a-4a3d-4824-8b6f-76353ee810b2" start_index="0" end="dbd04a19-6331-4172-a58a-4d60900d694d" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="38879d43-2874-4885-a26d-ab2b83d1b26e" start_index="0" end="f58f64d0-7b7f-4edb-be3a-92c507043af8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fdaca84b-4958-4865-bc66-78900f3ec9c4" start_index="0" end="678f910a-4a3d-4824-8b6f-76353ee810b2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c9c99a70-1abc-4079-b395-72f5054c8bee" start_index="0" end="9f7a391c-b18f-4709-8e5e-6d9f9fdd69ca" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d8b0e1b2-7745-44b4-bd4a-a3fcf38bfec1" start_index="0" end="dbd04a19-6331-4172-a58a-4d60900d694d" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-1799.98892276833" eyeY="11234.0405299291" eyeZ="13572.5055440615" lookX="7169.3705145652" lookY="-8234.0405299291" lookZ="-14576.9115499209" upX="0.110502552068524" upY="0.96814764037811" upZ="-0.224676061067141" />
  </Cameras>
</Workspace>