<Workspace Version="1.0.0.1180" X="-196.545295419092" Y="309.331046474309" zoom="1.02503137053572" Name="Analytical.CreateLineBoundaryCondition" Description="Create Line Boundary Condition from Analytical Line" ID="dacf0406-62db-4dad-93e4-a78d35704d89" Category="SteamNodes.Analytical">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e1dd0939-99d3-4dd6-97bc-f15b9598b404" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="0" y="84.2183333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="0;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="dfedcb74-6286-47d6-bf86-18ba0f7099c7" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="235" y="31.2183333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="15a267e3-83b7-4f8d-a246-147cd46a2833" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="767" y="27" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="4d4b9f47-3d4f-491d-b69c-fdf914e10d63" type="PythonNodeModels.PythonNode" nickname="Python Script" x="543" y="27" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <Script>#python nodes in dynamo 1.0
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
from System.Collections.Generic import *

doc = DocumentManager.Instance.CurrentDBDocument

elt=UnwrapElement(IN[0])

R=float(IN[1])

bc=[]
# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)

for e in elt:
	s=Autodesk.Revit.DB.Structure.TranslationRotationValue.Fixed
	a=doc.Create.NewLineBoundaryConditions(e,s,R,s,R,s,R,s,R)
	bc.append(a)

# End Transaction
TransactionManager.Instance.TransactionTaskDone()

OUT =bc</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="4a568993-f486-4c0e-88e2-5d001627783a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Analytical Beams" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e1dd0939-99d3-4dd6-97bc-f15b9598b404" start_index="0" end="4d4b9f47-3d4f-491d-b69c-fdf914e10d63" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dfedcb74-6286-47d6-bf86-18ba0f7099c7" start_index="0" end="4d4b9f47-3d4f-491d-b69c-fdf914e10d63" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4d4b9f47-3d4f-491d-b69c-fdf914e10d63" start_index="0" end="15a267e3-83b7-4f8d-a246-147cd46a2833" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4a568993-f486-4c0e-88e2-5d001627783a" start_index="0" end="dfedcb74-6286-47d6-bf86-18ba0f7099c7" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>