<Workspace Version="1.0.0.1180" X="-203.818531168186" Y="131.155757380531" zoom="1.22328547102291" Name="Element.MakeParts" Description="Create Parts from valid elements" ID="b21a82ad-addc-4961-a729-a01eefd21185" Category="SteamNodes.Element">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a8cc23e9-447b-487e-91f7-98a13600772a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-76.822107808976" y="40.5006338731702" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="efe388d0-19d0-4bd0-8d0c-886ffb07153e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="886.177892191024" y="82.5006338731702" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Parents" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="be031148-ebe1-4d8c-bf27-7797f03ed2a6" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="886.177892191024" y="-1.49936612682977" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Parts" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="a580a970-a872-4415-a60a-55d29f33f4b7" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Element.GetParts" x="655.177892191024" y="-1.49936612682977" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <ID value="7bffd864-393c-4d43-9cd2-1a0a1c6b34fc" />
      <Name value="Element.GetParts" />
      <Description value="Get parts for the elements from Input. Returns Parts and Parent elements" />
      <Inputs>
        <Input value="List" />
      </Inputs>
      <Outputs>
        <Output value="Parts" />
        <Output value="Parents" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <PythonNodeModels.PythonNode guid="5eb805ba-fc3e-44f6-88ea-920ef8b2d09d" type="PythonNodeModels.PythonNode" nickname="Python Script" x="431.177892191024" y="40.5006338731702" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#python nodes in dynamo 1.0
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#feed IN[0] with elements
elts = []
Ids = []
Parts=[]
for i in IN[0]:
	elts.append(UnwrapElement(i))

for e in elts:
	Ids.append(e.Id)
	
IDS = List[ElementId](Ids)

# Start Transaction tt
TransactionManager.Instance.EnsureInTransaction(doc)

a=PartUtils.CreateParts(doc, IDS)
doc.Regenerate()

# End Transaction
TransactionManager.Instance.TransactionTaskDone()

OUT = elts</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="072b5f15-cd12-4ddc-bf4b-8426865dfa54" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="123.177892191024" y="44.7139672065036" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="a8cc23e9-447b-487e-91f7-98a13600772a" start_index="0" end="072b5f15-cd12-4ddc-bf4b-8426865dfa54" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a580a970-a872-4415-a60a-55d29f33f4b7" start_index="0" end="be031148-ebe1-4d8c-bf27-7797f03ed2a6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5eb805ba-fc3e-44f6-88ea-920ef8b2d09d" start_index="0" end="a580a970-a872-4415-a60a-55d29f33f4b7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5eb805ba-fc3e-44f6-88ea-920ef8b2d09d" start_index="0" end="efe388d0-19d0-4bd0-8d0c-886ffb07153e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="072b5f15-cd12-4ddc-bf4b-8426865dfa54" start_index="0" end="5eb805ba-fc3e-44f6-88ea-920ef8b2d09d" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>