<Workspace Version="1.0.0.1180" X="170.18010859375" Y="343.372140421438" zoom="1.10052612463663" Name="Parts.Getparents" Description="Returns parents of selected Parts" ID="133d6516-1e16-4281-b8f0-8d7ffb4538bb" Category="SteamNodes.Parts">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="4bb00544-8cfe-4b1f-8e15-325cfa799aca" type="PythonNodeModels.PythonNode" nickname="Python Script" x="484" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#python nodes in dynamo 1.0
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

#unwrap all elements to use with API
elements = []
for i in IN[0]:
	elements.append(UnwrapElement(i))
	
# "Start" the transaction
TransactionManager.Instance.EnsureInTransaction(doc)

elementlist = list()
for item in elements:
    sourcelist = list()
    for source in item.GetSourceElementIds():
        sourcelist.append(doc.GetElement(source.HostElementId))
    if len(sourcelist) &lt; 2:
        elementlist.append(sourcelist[0])
    else:
        elementlist.append(sourcelist)



# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()


#Assign your output to the OUT variable
OUT = (elementlist)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="b54dcb61-372b-4ad8-9dec-ad884021a2ea" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="176" y="4.21833333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a8cb2c4a-54e6-4895-93bb-5f2a95a756cc" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Parts" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="7fb2609c-4905-40a7-9396-d30a05dd9a00" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="708" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="4bb00544-8cfe-4b1f-8e15-325cfa799aca" start_index="0" end="7fb2609c-4905-40a7-9396-d30a05dd9a00" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b54dcb61-372b-4ad8-9dec-ad884021a2ea" start_index="0" end="4bb00544-8cfe-4b1f-8e15-325cfa799aca" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a8cb2c4a-54e6-4895-93bb-5f2a95a756cc" start_index="0" end="b54dcb61-372b-4ad8-9dec-ad884021a2ea" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>