<Workspace Version="1.2.0.2690" X="157" Y="106" zoom="1" Name="Tool.PlaceViewsOnExistingSheets" Description="Place the views on the sheets at the points you provide." ID="2de3ad3e-ab86-4a13-9ecc-75b0cac20dcd" Category="SteamNodes.Tool">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="25d47412-afe8-477b-a606-46c52eac6a89" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#python nodes in dynamo 1.2
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

sheets = []
for i in IN[0]:
	sheets.append(UnwrapElement(i))
views=[]	
for i in IN[1]:
	views.append(UnwrapElement(i))
points=[]	
for i in IN[2]:
	points.append(UnwrapElement(i).ToXyz())

# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)
viewport=[]
for s,v,p in zip(sheets,views,points):
	try:
		a=Viewport.Create(doc, s.Id,v.Id, p)
	except:
		a="View is already placed"
	viewport.append(a)

# End Transaction
TransactionManager.Instance.TransactionTaskDone()

OUT=viewport</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="2355ee55-1796-4764-b5aa-e112e02b91e6" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Sheet" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="43734756-bbb1-4da6-ae12-75ab01397d54" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="150" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="View" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="eaffc730-ea80-4b7e-9743-53ab23bd5aa1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="300" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Point" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="fdab7ca2-12c2-4560-88d9-47580e98e25b" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="447" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Viewport" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="25d47412-afe8-477b-a606-46c52eac6a89" start_index="0" end="fdab7ca2-12c2-4560-88d9-47580e98e25b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2355ee55-1796-4764-b5aa-e112e02b91e6" start_index="0" end="25d47412-afe8-477b-a606-46c52eac6a89" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="43734756-bbb1-4da6-ae12-75ab01397d54" start_index="0" end="25d47412-afe8-477b-a606-46c52eac6a89" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="eaffc730-ea80-4b7e-9743-53ab23bd5aa1" start_index="0" end="25d47412-afe8-477b-a606-46c52eac6a89" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>