<Workspace Version="0.8.2.2392" X="-120.952373200597" Y="357.717045697757" zoom="0.585500843300343" Name="DividedSurface.VerticalIntersectsByEndpointsAndFunction" Description="Creates a number of vertical intersects (reference planes) for a divided surface based on the path between between two points. The spacing can be controlled by a function. You may need to switch start point and end point." ID="5c549d57-80a8-48b9-8eb4-c93ecdbc30b7" Category="Clockwork.Revit.Elements.DividedSurface.Actions">
  <NamespaceResolutionMap>
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="ReferencePlane" resolvedName="Revit.Elements.ReferencePlane" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="DividedSurface" resolvedName="Revit.Elements.DividedSurface" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Symbol guid="de4ee521-d19f-4046-90e2-749c4add666e" type="Dynamo.Nodes.Symbol" nickname="Input" x="1851.01752986781" y="110.688712560419" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="dividedSurface : DividedSurface" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="1b41fe9c-cefc-4707-a8e4-dcdb3d8d226c" type="Dynamo.Nodes.Symbol" nickname="Input" x="61.5574275207393" y="54.399587111351" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="startPoint : Autodesk.Point" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="77724451-d135-4507-9ba7-c5d636637a96" type="Dynamo.Nodes.Symbol" nickname="Input" x="78.5574275207393" y="137.972920444684" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="endPoint : Autodesk.Point" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="953cdc3a-a06b-4f71-a5d9-30a462134257" type="Dynamo.Nodes.Symbol" nickname="Input" x="136.557427520739" y="221.546253778018" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="subdivisions : int" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="02de61aa-b9a1-4c1d-be46-e10e9bc97000" type="Dynamo.Nodes.Output" nickname="Output" x="2516.11691948472" y="182.256112256919" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="dividedSurface" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Output guid="1a5794e0-884d-48cd-ba01-d524fd46214d" type="Dynamo.Nodes.Output" nickname="Output" x="2216.91919037229" y="290.086235228525" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="intersects" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Function guid="4dc9436e-9b85-46d0-b480-0df09b36bb7a" type="Dynamo.Nodes.Function" nickname="DividedSurface.AddIntersect" x="2212.2008257773" y="180.824544175041" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <ID value="e29fe7ec-cf80-41fd-a1a1-d55b01e15697" />
      <Name value="Add Intersect To Divided Surface" />
      <Description value="Adds an intersect to a divided surface" />
      <Inputs>
        <Input value="dividedSurface" />
        <Input value="element" />
      </Inputs>
      <Outputs>
        <Output value="dividedSurface" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Symbol guid="435faafd-df7d-4185-9133-b29e3f279149" type="Dynamo.Nodes.Symbol" nickname="Input" x="972.03472759493" y="51.158703285672" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="func" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Function guid="3cf8fc4c-93a5-4f22-a913-448265059895" type="Dynamo.Nodes.Function" nickname="List.NormalizedSequenceByFunction" x="1117.09491068996" y="112.631192292215" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <ID value="f584aeed-f101-459d-80d1-174c09579060" />
      <Name value="Normalized Sequence by Function" />
      <Description value="Creates a sequence of N values between 0 and 1 driven by a function" />
      <Inputs>
        <Input value="func" />
        <Input value="n" />
      </Inputs>
      <Outputs>
        <Output value="seq" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.CodeBlockNodeModel guid="b977d0cd-792e-40cb-9775-60c9fb1942d6" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="390" y="123.213333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="// Project the points to the XY plane and create a line between them&#xA;p1 = Autodesk.Point.ByCoordinates(startp.X,startp.Y);&#xA;p2 = Autodesk.Point.ByCoordinates(endp.X,endp.Y);&#xA;curve1 = Line.ByStartPointEndPoint(p1,p2);&#xA;// Find vector orthogonal to line&#xA;vec1 = Vector.ByTwoPoints(p1,p2).Normalized();&#xA;vec2 = vec1.Cross(Vector.ZAxis());&#xA;vec3 = vec2.Scale(curve1.Length/10);&#xA;subdiv+1;" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="1bf334d5-63ce-4259-a40a-a6cd7435ca16" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1382.83218741485" y="188.422929719431" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="seq2 = List.RestOfItems(seq);&#xA;seq3 = List.TakeItems(seq2,List.Count(seq2)-1);&#xA;// Create points for subdivisions&#xA;cpoints = curve1.PointAtParameter(seq3);&#xA;// Create a set of orthogonal planes to curve 1&#xA;seq1 = ReferencePlane.ByStartPointEndPoint(cpoints.Add(vec3),cpoints.Subtract(vec3));" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="de4ee521-d19f-4046-90e2-749c4add666e" start_index="0" end="4dc9436e-9b85-46d0-b480-0df09b36bb7a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1b41fe9c-cefc-4707-a8e4-dcdb3d8d226c" start_index="0" end="b977d0cd-792e-40cb-9775-60c9fb1942d6" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="77724451-d135-4507-9ba7-c5d636637a96" start_index="0" end="b977d0cd-792e-40cb-9775-60c9fb1942d6" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="953cdc3a-a06b-4f71-a5d9-30a462134257" start_index="0" end="b977d0cd-792e-40cb-9775-60c9fb1942d6" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="4dc9436e-9b85-46d0-b480-0df09b36bb7a" start_index="0" end="02de61aa-b9a1-4c1d-be46-e10e9bc97000" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="435faafd-df7d-4185-9133-b29e3f279149" start_index="0" end="3cf8fc4c-93a5-4f22-a913-448265059895" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="3cf8fc4c-93a5-4f22-a913-448265059895" start_index="0" end="1bf334d5-63ce-4259-a40a-a6cd7435ca16" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="b977d0cd-792e-40cb-9775-60c9fb1942d6" start_index="2" end="1bf334d5-63ce-4259-a40a-a6cd7435ca16" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="b977d0cd-792e-40cb-9775-60c9fb1942d6" start_index="5" end="1bf334d5-63ce-4259-a40a-a6cd7435ca16" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="b977d0cd-792e-40cb-9775-60c9fb1942d6" start_index="6" end="3cf8fc4c-93a5-4f22-a913-448265059895" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="1bf334d5-63ce-4259-a40a-a6cd7435ca16" start_index="3" end="1a5794e0-884d-48cd-ba01-d524fd46214d" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1bf334d5-63ce-4259-a40a-a6cd7435ca16" start_index="3" end="4dc9436e-9b85-46d0-b480-0df09b36bb7a" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>