<Workspace Version="0.8.2.2392" X="30" Y="313.557422640031" zoom="0.808460634547591" Name="Mesh.FaceVertices" Description="Gets the vertices of each face of a given mesh" ID="21e0126f-dca2-47a0-84f3-b403bc0e6d71" Category="Clockwork.Geometry.Mesh.Query">
  <NamespaceResolutionMap>
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="DesignScript.Mesh" resolvedName="Autodesk.DesignScript.Geometry.Mesh" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Symbol guid="90f80594-ced4-4c1a-81ce-8088de4cd33b" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="mesh : DesignScript.Mesh" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="eab0df2d-0d15-4390-bc53-ee706609e68b" type="Dynamo.Nodes.Output" nickname="Output" x="767" y="87.8666666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="vertices" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.CodeBlockNodeModel guid="8680c803-a8e4-4eb7-abc5-008c1d2e5c51" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="332" y="4.21333333333334" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="vp = m.VertexPositions;&#xA;fi = m.FaceIndices;&#xA;a = List.GetItemAtIndex(vp,fi.A);&#xA;b = List.GetItemAtIndex(vp,fi.B);&#xA;c = List.GetItemAtIndex(vp,fi.C);&#xA;List.Transpose({a,b,c});" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="90f80594-ced4-4c1a-81ce-8088de4cd33b" start_index="0" end="8680c803-a8e4-4eb7-abc5-008c1d2e5c51" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="8680c803-a8e4-4eb7-abc5-008c1d2e5c51" start_index="5" end="eab0df2d-0d15-4390-bc53-ee706609e68b" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>