<Workspace Version="0.8.2.2392" X="30" Y="389.47899009901" zoom="1.3990099009901" Name="Plane.ByFirst3Points" Description="Returns a plane, its origin and its normal based on the first three XYZs in a given list" ID="7ac4f102-aa4a-4c97-b637-18e158f79348" Category="Clockwork.Geometry.Plane.Create">
  <NamespaceResolutionMap>
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Symbol guid="63be13c7-b965-4380-8fa6-0a4dbb0edc64" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="7.105427357601E-15" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="points : Autodesk.Point[]" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.CodeBlockNodeModel guid="928a37da-e06c-4f40-b06f-42cf7cbba36a" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="340" y="4.21333333333334" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="Plane.ByBestFitThroughPoints(List.TakeItems(seq,3));" ShouldFocus="false" />
    <Dynamo.Nodes.Output guid="601bc803-4e61-45fa-9282-696d0e3dc2bd" type="Dynamo.Nodes.Output" nickname="Output" x="939" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="plane" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="63be13c7-b965-4380-8fa6-0a4dbb0edc64" start_index="0" end="928a37da-e06c-4f40-b06f-42cf7cbba36a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="928a37da-e06c-4f40-b06f-42cf7cbba36a" start_index="0" end="601bc803-4e61-45fa-9282-696d0e3dc2bd" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>