<Workspace Version="0.9.0.3067" X="41" Y="286.155411655874" zoom="1.18593894542091" Name="Wall.CreationMethod" Description="Retrieves the creation method of a given wall" ID="78585c2b-d4fd-4acd-96ac-7114dd286e20" Category="Clockwork.Revit.Elements.Wall.Query">
  <NamespaceResolutionMap>
    <ClassMap partialName="Wall" resolvedName="Revit.Elements.Wall" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Function guid="e8f2edca-cf74-4cf1-aa9c-4058f9fd139e" type="Dynamo.Nodes.Function" nickname="TurnIntoList" x="232.059282371295" y="27.3346333853354" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="Turn Into List" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="" />
      </Inputs>
      <Outputs>
        <Output value="seq" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <PythonNodeModels.PythonNode guid="33c18a20-cc98-4a66-a5f0-cfacba84305c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="432" y="26" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

wallinstances = UnwrapElement(IN[0])
methodlist = list()
for item in wallinstances:
	try:
		if item.GetType().Name == 'Wall':
			methodlist.append('Standard')
		elif item.GetType().Name == 'FaceWall':
			methodlist.append('By Face')
		elif item.GetType().Name == 'FamilyInstance':
			methodlist.append('In-Place')
		else:
			methodlist.append('No Wall')
	except:
		methodlist.append('No Wall')
OUT = methodlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.Symbol guid="4d7090a5-55aa-4d07-aa91-3d027092bbd0" type="Dynamo.Nodes.Symbol" nickname="Input" x="49.7496099843992" y="-49.3978159126367" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="wall" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="2724754f-5a11-4d34-922f-0d3f831e9f6d" type="Dynamo.Nodes.Output" nickname="Output" x="906.860374414977" y="-50.5928237129484" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="creationMethod" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Function guid="c5b397d7-b11d-4a87-9096-f58a593b3016" type="Dynamo.Nodes.Function" nickname="ReturnListOrSingleValue" x="629.860374414977" y="-50.5928237129484" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <ID value="44ac4888-4aa4-49a9-9344-23b729c11df9" />
      <Name value="ReturnListOrSingleValue" />
      <Description value="If the item in input #1 is not a list, only the first item of the list in input #2 will be returned." />
      <Inputs>
        <Input value="unknownItem" />
        <Input value="seq" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="e8f2edca-cf74-4cf1-aa9c-4058f9fd139e" start_index="0" end="33c18a20-cc98-4a66-a5f0-cfacba84305c" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="33c18a20-cc98-4a66-a5f0-cfacba84305c" start_index="0" end="c5b397d7-b11d-4a87-9096-f58a593b3016" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="4d7090a5-55aa-4d07-aa91-3d027092bbd0" start_index="0" end="e8f2edca-cf74-4cf1-aa9c-4058f9fd139e" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="4d7090a5-55aa-4d07-aa91-3d027092bbd0" start_index="0" end="c5b397d7-b11d-4a87-9096-f58a593b3016" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="c5b397d7-b11d-4a87-9096-f58a593b3016" start_index="0" end="2724754f-5a11-4d34-922f-0d3f831e9f6d" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>