<Workspace Version="0.9.0.3067" X="0" Y="0" zoom="1" Name="WallLocationLine.CoreInterior" Description="Returns the WallLocationLine option for CoreInterior" ID="b3d295c0-9e81-48d9-a651-35a695e149f9" Category="Clockwork.Revit.Elements.WallLocationLine.Query">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="62d3116a-955c-4458-bcda-49cd5a3cbf37" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" inputcount="0">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

OUT = WallLocationLine.CoreInterior</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.Output guid="0d54dfa3-7ad6-4c80-959d-1c8429eac09f" type="Dynamo.Nodes.Output" nickname="Output" x="419" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="CoreInterior" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Output guid="9de71ed0-5bec-412c-b4a7-f25b4edf47f5" type="Dynamo.Nodes.Output" nickname="Output" x="449" y="73" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="int" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.CodeBlockNodeModel guid="346d26a8-079f-4a5c-a052-ae706c175a2d" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="255" y="77.2183333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="5;" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="62d3116a-955c-4458-bcda-49cd5a3cbf37" start_index="0" end="0d54dfa3-7ad6-4c80-959d-1c8429eac09f" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="346d26a8-079f-4a5c-a052-ae706c175a2d" start_index="0" end="9de71ed0-5bec-412c-b4a7-f25b4edf47f5" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>