<Workspace Version="0.7.5.3566" X="507.897942482459" Y="42.3569887304601" zoom="1.09218965916194" Description="This node will generate a Colored Surface Display Style from inputs of points, values, and instance surface for analysis to be aplied to. Also, use color and legend settings (part of archi-lab package) to create style colors and visibility." Category="Archi-lab_Grimshaw.Analysis" Name="Colored Surface Display Style" ID="20a4d55a-2bb3-4ac3-8801-4ae3012f527e">
  <Elements>
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="419499e0-f96d-4e43-af52-6bec312aaff2" nickname="Python Script" x="221.307337743789" y="105.222307580199" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="12">
      <Script>#Copyright(c) 2015, Konrad K Sobon
# @arch_laboratory, http://archi-lab.net

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Analysis import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

values = IN[0]
surfaces = IN[1]
UVPoints = IN[2]

colorSettings = IN[3]
legendSettings = IN[4]
styleSettings = IN[5]

displayStyleName = IN[6]
analysisResultName = IN[7]
analysisResultDescription = IN[8]
unitNames = IN[9]
unitMultipliers = IN[10]
displayUnit = IN[11]

message = None

def getFace(element):
	#create geometry options/compute references
	geoOptions = Options()
	geoOptions.ComputeReferences = True
	#extract geometry
	geoElement = element.get_Geometry(geoOptions)
	geoSet = List[GeometryInstance]()
	elemIter = geoElement.GetEnumerator()
	elemIter.Reset()
	while elemIter.MoveNext():
		curElem = elemIter.Current
		geoSet.Add(curElem)
	#extract faces from solids
	for i in geoSet:
		solids = i.SymbolGeometry
		for i in solids:
			faces = i.Faces
	return faces[0]

#"Start" the transaction
TransactionManager.Instance.EnsureInTransaction(doc)

#create spatial field manager if one doesnt already exist
sfm = SpatialFieldManager.GetSpatialFieldManager(doc.ActiveView)
if sfm == None:
	sfm = SpatialFieldManager.CreateSpatialFieldManager(doc.ActiveView, 1)
sfm.Clear()

#get result schema index if existing else crete one
regResults = sfm.GetRegisteredResults()
if len(regResults) != 0:
	for i in regResults:
		if sfm.GetResultSchema(i).Name == analysisResultName:
			resultSchema = sfm.GetResultSchema(i)
else:
	resultSchema = AnalysisResultSchema(analysisResultName, analysisResultDescription)

names = List[str]()
multipliers = List[float]()
for i,j in zip(unitMultipliers, unitNames):
	multipliers.Add(i)
	names.Add(j)
resultSchema.SetUnits(names, multipliers)

for i in range(0, resultSchema.GetNumberOfUnits(), 1):
	if resultSchema.GetUnitsName(i) == displayUnit:
		resultSchema.CurrentUnits = i
		message = "Success! Remember that your current \ndisplay units are set to " + displayUnit
	else:
		continue
if resultSchema.GetUnitsName(resultSchema.CurrentUnits) != displayUnit:
	message = "Display Units supplied not available. \nEither add those units to results or \nspecify one of the already supplied."

schemaIndex = sfm.RegisterResult(resultSchema)

#unwrap surfaces
elements = []
for i in surfaces:
	elements.append(UnwrapElement(i))

if not any(isinstance(item, list) for item in values):
	face = getFace(elements[0])
	#create a spatial field primitive for each face and add to schema
	idx = sfm.AddSpatialFieldPrimitive(face.Reference)
	doubleList = List[float]()
	valList = List[ValueAtPoint]()
	fieldPointsUV = List[Autodesk.Revit.DB.UV]()
	for i,j in zip(values, UVPoints):
		doubleList.Add(float(i))
		valList.Add(ValueAtPoint(doubleList))
		doubleList.Clear()
		fieldPointsUV.Add(j)
	vals = FieldValues(valList)
	pnts = FieldDomainPointsByUV(fieldPointsUV)
	sfm.UpdateSpatialFieldPrimitive(idx, pnts, vals, schemaIndex)
	valList.Clear()
	fieldPointsUV.Clear()
else:
	for element, value, UVPoint in zip(elements, values, UVPoints):
		face = getFace(element)
		idx = sfm.AddSpatialFieldPrimitive(face.Reference)
		doubleList = List[float]()
		valList = List[ValueAtPoint]()
		fieldPointsUV = List[Autodesk.Revit.DB.UV]()
		for i,j in zip(value, UVPoint):
			doubleList.Add(float(i))
			valList.Add(ValueAtPoint(doubleList))
			doubleList.Clear()
			fieldPointsUV.Add(j)
		vals = FieldValues(valList)
		pnts = FieldDomainPointsByUV(fieldPointsUV)
		sfm.UpdateSpatialFieldPrimitive(idx, pnts, vals, schemaIndex)
		valList.Clear()
		fieldPointsUV.Clear()

#create display style for colored surfaces and apply to current view
collector = FilteredElementCollector(doc)
collection = collector.OfClass(AnalysisDisplayStyle).ToElements()
displayStyle = []
for i in collection:
	if i.Name == displayStyleName and i.HasColoredSurfaceSettings():
		displayStyle.append(i)
	elif i.Name == displayStyleName and not i.HasColoredSurfaceSettings():
		message = "Specified Display Style name already \nexists; please supply different name"
	else:
		continue
if len(displayStyle) == 0:
	try:
		analysisDisplayStyle = AnalysisDisplayStyle.CreateAnalysisDisplayStyle(doc, displayStyleName, styleSettings, colorSettings, legendSettings)
	except:
		pass
else:
	analysisDisplayStyle = displayStyle[0]
	analysisDisplayStyle.SetLegendSettings(legendSettings)
	analysisDisplayStyle.SetColorSettings(colorSettings)
	analysisDisplayStyle.SetColoredSurfaceSettings(styleSettings)

try:
	doc.ActiveView.AnalysisDisplayStyleId = analysisDisplayStyle.Id
except:
	pass

# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable
if message != None:
	OUT = message
else:
	OUT = 0</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="9bcf04af-7850-4242-808b-ce7abcff30b8" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Values" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="efc26e58-d21b-4b7c-839a-558c9000e840" nickname="Input" x="0" y="54.3386639507911" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Surfaces" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="7768d85b-c6fa-4029-b696-c0ae946cde50" nickname="Input" x="0" y="106.597733639643" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="UV Points" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="52b1fd0d-aa5d-4d41-83a2-ac64f9dad11f" nickname="Input" x="0" y="159.550001415808" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Color Settings" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="42fb706e-8c3f-4ce3-8549-0909276cffd7" nickname="Input" x="-0.994031645109658" y="211.333626762121" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Legend Settings" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="d54417b4-4300-4798-91cd-5b26b6d41705" nickname="Input" x="-3.97612658043863" y="264.912557186483" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Colored Surface Settings" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="134bc83b-feec-47ed-a992-6e0cdd1a185b" nickname="Input" x="-5.02102894946188" y="317.56064186241" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Display Style Name" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="404c2755-1d58-4a08-b79e-5f2c3926e9c5" nickname="Input" x="-3.7118612456145" y="369.492104970679" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Analysis Result Name" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="d5314d81-30c7-49d5-94a0-e0d996744bb1" nickname="Input" x="-6.1864354093575" y="419.271851339087" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Analysis Result Description" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="5eaccffc-3448-4e55-a37e-3c96ff3413a6" nickname="Input" x="-3.7118612456145" y="470.288884789368" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Units Names" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="dd804499-e7cb-47f3-ac77-d10c9fc81388" nickname="Input" x="-8.84337420078953" y="520.604956255256" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Units Multipliers" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="5ad6d9e3-0166-4f97-b97f-fe04ceace478" nickname="Input" x="-8.45772056140731" y="575.175001834539" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Display Unit" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="85cf7499-dc1f-49d1-9fc6-801aa57ac647" nickname="Output" x="405.363106694286" y="103.273786611427" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="OUT" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="419499e0-f96d-4e43-af52-6bec312aaff2" start_index="0" end="85cf7499-dc1f-49d1-9fc6-801aa57ac647" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="9bcf04af-7850-4242-808b-ce7abcff30b8" start_index="0" end="419499e0-f96d-4e43-af52-6bec312aaff2" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="efc26e58-d21b-4b7c-839a-558c9000e840" start_index="0" end="419499e0-f96d-4e43-af52-6bec312aaff2" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="7768d85b-c6fa-4029-b696-c0ae946cde50" start_index="0" end="419499e0-f96d-4e43-af52-6bec312aaff2" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="52b1fd0d-aa5d-4d41-83a2-ac64f9dad11f" start_index="0" end="419499e0-f96d-4e43-af52-6bec312aaff2" end_index="3" portType="0" />
    <Dynamo.Models.ConnectorModel start="42fb706e-8c3f-4ce3-8549-0909276cffd7" start_index="0" end="419499e0-f96d-4e43-af52-6bec312aaff2" end_index="4" portType="0" />
    <Dynamo.Models.ConnectorModel start="d54417b4-4300-4798-91cd-5b26b6d41705" start_index="0" end="419499e0-f96d-4e43-af52-6bec312aaff2" end_index="5" portType="0" />
    <Dynamo.Models.ConnectorModel start="134bc83b-feec-47ed-a992-6e0cdd1a185b" start_index="0" end="419499e0-f96d-4e43-af52-6bec312aaff2" end_index="6" portType="0" />
    <Dynamo.Models.ConnectorModel start="404c2755-1d58-4a08-b79e-5f2c3926e9c5" start_index="0" end="419499e0-f96d-4e43-af52-6bec312aaff2" end_index="7" portType="0" />
    <Dynamo.Models.ConnectorModel start="d5314d81-30c7-49d5-94a0-e0d996744bb1" start_index="0" end="419499e0-f96d-4e43-af52-6bec312aaff2" end_index="8" portType="0" />
    <Dynamo.Models.ConnectorModel start="5eaccffc-3448-4e55-a37e-3c96ff3413a6" start_index="0" end="419499e0-f96d-4e43-af52-6bec312aaff2" end_index="9" portType="0" />
    <Dynamo.Models.ConnectorModel start="dd804499-e7cb-47f3-ac77-d10c9fc81388" start_index="0" end="419499e0-f96d-4e43-af52-6bec312aaff2" end_index="10" portType="0" />
    <Dynamo.Models.ConnectorModel start="5ad6d9e3-0166-4f97-b97f-fe04ceace478" start_index="0" end="419499e0-f96d-4e43-af52-6bec312aaff2" end_index="11" portType="0" />
  </Connectors>
  <Notes />
</Workspace>