<Workspace Version="1.3.0.875" X="781.396666666667" Y="452.83" zoom="1.1575" ScaleFactor="1" Name="Export To NWC" Description="this one for single view" ID="7148c9a8-7733-4c68-a2dd-6ada682e7ac4" Category="Bakery.Construction.Navisworks">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="fd5e91d4-a240-412a-9b3d-01b66242beba" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#python nodes in dynamo 1.0
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

#view = []
#for i in IN[0]:
#	views.append(UnwrapElement(i))
folder=IN[0]
name=IN[1]
exportoptionbldr=IN[2]

c=doc.Export(folder,name,exportoptionbldr)



# End Transaction
#TransactionManager.Instance.TransactionTaskDone()

OUT=c</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="ed05afc2-9610-4db1-b758-c5847433f359" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-544" y="-80" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="directoryPath" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9d9e0b92-68ea-4284-842d-fc1f2d5bb8d5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="150" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="fileName" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="dcf7e5a8-46cd-4a3d-85f4-bfab7255591a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-42.6205903527718" y="329.373650107991" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="NavisworksExportOptions" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="cbdec374-7a33-4972-84c5-b8726b7d43bf" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="OUT" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <CoreNodeModels.FromObject guid="08698d2d-e640-4131-b4ee-08cf865b8e25" type="CoreNodeModels.FromObject" nickname="String from Object" x="-357.333333333333" y="-93.9999999999999" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.FromObject>
    <Dynamo.Graph.Nodes.ZeroTouch.DSVarArgFunction guid="9350ee62-6ccd-4b61-9760-27da1d0c6515" type="Dynamo.Graph.Nodes.ZeroTouch.DSVarArgFunction" nickname="String.Concat" x="-204.370845799743" y="23.1699526580051" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.String.Concat@string[]" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSVarArgFunction>
    <CoreNodeModels.Input.StringInput guid="f33fc12f-f49c-475e-9f70-52ce3bdc0ff5" type="CoreNodeModels.Input.StringInput" nickname="String" x="-299.955435279034" y="75.822574863833" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>\</System.String>
      <System.String value="\" />
    </CoreNodeModels.Input.StringInput>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="fd5e91d4-a240-412a-9b3d-01b66242beba" start_index="0" end="cbdec374-7a33-4972-84c5-b8726b7d43bf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ed05afc2-9610-4db1-b758-c5847433f359" start_index="0" end="08698d2d-e640-4131-b4ee-08cf865b8e25" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9d9e0b92-68ea-4284-842d-fc1f2d5bb8d5" start_index="0" end="fd5e91d4-a240-412a-9b3d-01b66242beba" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dcf7e5a8-46cd-4a3d-85f4-bfab7255591a" start_index="0" end="fd5e91d4-a240-412a-9b3d-01b66242beba" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="08698d2d-e640-4131-b4ee-08cf865b8e25" start_index="0" end="9350ee62-6ccd-4b61-9760-27da1d0c6515" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9350ee62-6ccd-4b61-9760-27da1d0c6515" start_index="0" end="fd5e91d4-a240-412a-9b3d-01b66242beba" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f33fc12f-f49c-475e-9f70-52ce3bdc0ff5" start_index="0" end="9350ee62-6ccd-4b61-9760-27da1d0c6515" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>