<Workspace Version="1.2.1.3083" X="0" Y="0" zoom="1" Name="Get Elements By Workset Id" Description="" ID="14ed8d38-7bfb-4958-833c-f2ed0ba5e3ae" Category="Bakery.Revit.Document.Worksets">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="99ca7be1-7b1a-4681-88ca-47f5d800ff3d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="435.6" y="430" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="WORKSETID" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="1954467f-5ac8-4353-a0ad-70736489cfe8" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="878.48009001749" y="446.805300950265" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="8f8758f2-d656-4c18-94e4-b2c24047eec9" type="PythonNodeModels.PythonNode" nickname="Python Script" x="533.172765749658" y="599.669598276758" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

from System import Guid

import System

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)

import os.path

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

worksetId = IN[0]
worksetFilter = ElementWorksetFilter(worksetId)
collector = FilteredElementCollector(doc).WherePasses(worksetFilter).ToElements()
OUT = collector
</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="99ca7be1-7b1a-4681-88ca-47f5d800ff3d" start_index="0" end="8f8758f2-d656-4c18-94e4-b2c24047eec9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8f8758f2-d656-4c18-94e4-b2c24047eec9" start_index="0" end="1954467f-5ac8-4353-a0ad-70736489cfe8" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>