<Workspace Version="0.8.0.950" X="102.045641890625" Y="221.538324546875" zoom="1.545620359375" Name="Mirror an Element" ID="888c2901-ed8c-4bb1-a658-7749481fe527" Description="using python" Category="Bakery.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.Symbol guid="090f06d1-590a-4bf4-b0c4-838948577fb5" type="Dynamo.Nodes.Symbol" nickname="Input" x="10" y="9.99999999999999" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="elementList" />
    </Dynamo.Nodes.Symbol>
    <DSIronPythonNode.PythonNode guid="1ee55685-a25e-4237-9940-668ff0d98d56" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="362.312012480499" y="156.918876755071" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="2">
      <Script>import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import ElementTransformUtils, Plane

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

walls = UnwrapElement(IN[0])
planes = IN[1]
rvt_planes =list()
mirrored = list()
count = 0

def Dyn2RvtPlane(pl1):
	normal1 = pl1.Normal.ToXyz(True)
	origin1 = pl1.Origin.ToXyz(True)
	return Autodesk.Revit.DB.Plane(normal1, origin1)

TransactionManager.Instance.EnsureInTransaction(doc)
for p in planes:
	rvt_planes.append(Dyn2RvtPlane(p))
for w, rp in zip(walls, rvt_planes):
	try:
#		item.Flip()
		ElementTransformUtils.MirrorElement(doc, w.Id, rp)
		count += 1
	except:
		count += 0
TransactionManager.Instance.TransactionTaskDone()
		
OUT = "%s elements mirrored" %count</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Output guid="19c51152-2e8c-4390-8375-4c6783c86ed0" type="Dynamo.Nodes.Output" nickname="Output" x="863.312012480499" y="130.918876755071" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Out" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Symbol guid="361438f6-f24c-4f93-8130-6dd2d0ffb8ab" type="Dynamo.Nodes.Symbol" nickname="Input" x="-12.3624651501431" y="235.762706738009" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="planeList" />
    </Dynamo.Nodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="090f06d1-590a-4bf4-b0c4-838948577fb5" start_index="0" end="1ee55685-a25e-4237-9940-668ff0d98d56" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1ee55685-a25e-4237-9940-668ff0d98d56" start_index="0" end="19c51152-2e8c-4390-8375-4c6783c86ed0" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="361438f6-f24c-4f93-8130-6dd2d0ffb8ab" start_index="0" end="1ee55685-a25e-4237-9940-668ff0d98d56" end_index="1" portType="0" />
  </Connectors>
  <Notes />
</Workspace>