<Workspace Version="0.8.2.2371" X="-90.2675" Y="168.1875" zoom="0.8425" Name="one Room to its PolyCurves" Description="for list.map, nested" ID="ad1e854e-331e-4eec-96b8-1c8bc7206225" Category="Bakery.Geometry">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.Function guid="b509f87a-2ee4-4cf6-8ddf-4c7619b9cb83" type="Dynamo.Nodes.Function" nickname="Room.Boundaries" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False">
      <ID value="fb07f5d8-94b8-4985-bf2f-a54fe832aa66" />
      <Name value="Room.Boundaries" />
      <Description value="Gets a list of all boundary elements of a given room or area" />
      <Inputs>
        <Input value="Room(s)" />
      </Inputs>
      <Outputs>
        <Output value="Elements" />
        <Output value="Curves" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Function guid="13f4b573-4cbd-4f20-ac53-9141df1c7630" type="Dynamo.Nodes.Function" nickname="Group Curves" x="508.619144868921" y="26.3683348761473" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False">
      <ID value="c84855d4-eb7e-4574-86a5-04867486df63" />
      <Name value="Group Curves" />
      <Description value="This node will take any input of flat list of curves and group them into sublists containing &quot;joinable&quot; curves that is continous curves. They might form closed curves or open curves. Use PolyCurve.ByJoinedCurves to convert output groups of curves into single PolyCurves" />
      <Inputs>
        <Input value="Curves" />
      </Inputs>
      <Outputs>
        <Output value="Grouped Curves" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.DSFunction guid="7b78e653-2659-42a7-97e6-dbe956e48860" type="Dynamo.Nodes.DSFunction" nickname="PolyCurve.ByJoinedCurves" x="740.60088970577" y="24.7465656239276" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.PolyCurve.ByJoinedCurves@Autodesk.DesignScript.Geometry.Curve[]" />
    <Dynamo.Nodes.Output guid="3876eac1-1b9f-4a69-8e4d-3df2a2ace8d6" type="Dynamo.Nodes.Output" nickname="Output" x="989.60088970577" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="PolyCurve" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Symbol guid="a247074e-0cd9-431d-a63b-447fd7632794" type="Dynamo.Nodes.Symbol" nickname="Input" x="154" y="252" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="oneRoom" />
    </Dynamo.Nodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="b509f87a-2ee4-4cf6-8ddf-4c7619b9cb83" start_index="1" end="13f4b573-4cbd-4f20-ac53-9141df1c7630" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="13f4b573-4cbd-4f20-ac53-9141df1c7630" start_index="0" end="7b78e653-2659-42a7-97e6-dbe956e48860" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="7b78e653-2659-42a7-97e6-dbe956e48860" start_index="0" end="3876eac1-1b9f-4a69-8e4d-3df2a2ace8d6" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="a247074e-0cd9-431d-a63b-447fd7632794" start_index="0" end="b509f87a-2ee4-4cf6-8ddf-4c7619b9cb83" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>