<Workspace Version="0.8.2.2311" X="-76.6076816209198" Y="230.910309996291" zoom="0.97676875" Name="Set Workset for a Single Element" Description="use with list.map" ID="64aedabf-9c97-4b48-a69e-3b13c88e0be9" Category="Bakery.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.Symbol guid="08e380f9-f646-48fa-b934-8bee1e0dd057" type="Dynamo.Nodes.Symbol" nickname="Input" x="10" y="21.3651864801865" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="Element(s)" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="efb743cc-9e82-482f-8219-ad1e6c45df4b" type="Dynamo.Nodes.Symbol" nickname="Input" x="100.793282275101" y="142.762744272624" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="Workset" />
    </Dynamo.Nodes.Symbol>
    <DSIronPythonNode.PythonNode guid="781165eb-acac-4fea-901f-20d727e6252b" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="381.376352178755" y="34.0042793415365" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

faminsts = UnwrapElement(IN[0])
ws = UnwrapElement(IN[1])
wsId = ws.Id.IntegerValue
diditwork = ""
try:
	t = Transaction(doc, 'Setting value')
	t.Start()
	wsparam = faminsts.get_Parameter(BuiltInParameter.ELEM_PARTITION_PARAM)
	wsparamAsInt = wsparam.AsInteger()
	wsparam.Set(wsId)
	t.Commit
	diditwork = "Success"
except:
	diditwork = "Failed"
OUT = faminsts, ws, wsId, wsparam, wsparamAsInt, diditwork</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Output guid="5f3fac0a-f1b8-4a4c-9e65-73fe0c5cfadd" type="Dynamo.Nodes.Output" nickname="Output" x="815.972027972028" y="10" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Changed Element(s)" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="08e380f9-f646-48fa-b934-8bee1e0dd057" start_index="0" end="781165eb-acac-4fea-901f-20d727e6252b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="efb743cc-9e82-482f-8219-ad1e6c45df4b" start_index="0" end="781165eb-acac-4fea-901f-20d727e6252b" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="781165eb-acac-4fea-901f-20d727e6252b" start_index="0" end="5f3fac0a-f1b8-4a4c-9e65-73fe0c5cfadd" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>