<Workspace Version="1.0.0.1180" X="243" Y="186" zoom="1" Name="To Int" Description="" ID="568c0891-7142-453e-9a71-875fcac7968e" Category="Bakery.Math">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="83499486-dbca-48c6-98d1-88ea8db3c49b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN[0]
intlist = []
for x in dataEnteringNode:
	intlist.append(int(x))

#Assign your output to the OUT variable.
OUT = intlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e6fd3614-8b77-4bb0-b520-b7bb01e2b873" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="listIn" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="73f240e3-4c45-4d4c-9961-aee2d4b45e17" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="447" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="ints" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="83499486-dbca-48c6-98d1-88ea8db3c49b" start_index="0" end="73f240e3-4c45-4d4c-9961-aee2d4b45e17" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e6fd3614-8b77-4bb0-b520-b7bb01e2b873" start_index="0" end="83499486-dbca-48c6-98d1-88ea8db3c49b" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>