<Workspace Version="1.3.4.6666" X="401.468119514469" Y="238.303706838904" zoom="1.66537098414077" ScaleFactor="1" Name="HostedObject.FacingOrientation" Description="from old clockwork" ID="259e4bc1-da14-4656-ba55-90ebcf41fc28" Category="Bakery.Dynamo.ForkedNodes">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="8f1eab2b-f769-45c6-90e7-85aab135ce73" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

objinstances = UnwrapElement(IN[0])
vectorlist = list()
for item in objinstances:
	try:
		vectorlist.append(item.FacingOrientation.ToVector())
	except:
		vectorlist.append(list())
OUT = vectorlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="cb8c0486-56e1-4f1d-9efb-88baae68581d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="instances" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="0532d37c-5569-48df-9875-2b7bb1ce5e2e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="vectorlist" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="8f1eab2b-f769-45c6-90e7-85aab135ce73" start_index="0" end="0532d37c-5569-48df-9875-2b7bb1ce5e2e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cb8c0486-56e1-4f1d-9efb-88baae68581d" start_index="0" end="8f1eab2b-f769-45c6-90e7-85aab135ce73" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>