<Workspace Version="1.0.0.1180" X="586.911082669326" Y="50.3795652814664" zoom="1.130842140625" Name="Make Openings in Walls" Description="" ID="09165f27-9cf0-4225-b16b-894ac8cd6be8" Category="Bakery.Revit.Elements.Wall">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="9f0f9fd3-bf76-4bf2-b227-c6916948fe22" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="5">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager


doc = DocumentManager.Instance.CurrentDBDocument
openings = []

walls = IN[0]
points = IN[1]
direction = IN[2]
width = IN[3]
height = IN[4]

for idx in range(0,len(walls)):
	if direction[idx] == 'x':
		ULX=(points[idx]).X  - width[idx]/2
		ULY=(points[idx]).Y
		ULZ=(points[idx]).Z + height[idx]/2
			
		UL = XYZ(ULX/304.8,ULY/304.8,ULZ/304.8)
		
		DRX=(points[idx]).X + width[idx]/2
		DRY=(points[idx]).Y
		DRZ=(points[idx]).Z - height[idx]/2
		
		DR = XYZ(DRX/304.8,DRY/304.8,DRZ/304.8)
	else:
		ULX=(points[idx]).X
		ULY=(points[idx]).Y - width[idx]/2
		ULZ=(points[idx]).Z + height[idx]/2
			
		UL = XYZ(ULX/304.8,ULY/304.8,ULZ/304.8)
		
		DRX=(points[idx]).X
		DRY=(points[idx]).Y + width[idx]/2
		DRZ=(points[idx]).Z - height[idx]/2
		
		DR = XYZ(DRX/304.8,DRY/304.8,DRZ/304.8)
	
	TransactionManager.Instance.EnsureInTransaction(doc)
	opening = doc.Create.NewOpening(UnwrapElement(walls[idx]),UL,DR)
	TransactionManager.Instance.TransactionTaskDone()
	openings.append(opening)
	
OUT = openings</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="04af55dd-337b-463b-9aba-61e204514984" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="wallElements" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="fd84fcf1-a670-4cc4-8c18-116aa477c4db" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-252.572191839041" y="81.2525394994325" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="centroidPoint" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="73c980c4-2725-4720-b8ec-23237a0ba9f7" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-217.451206583317" y="220.043714417818" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="normalAxis" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="535c5ec0-2055-4d66-951c-f74c3ab13eb5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-141.978451033781" y="358.087634330763" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="widthMM" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="101bc430-fb48-43f4-acb9-f07f903f227c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="600" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="heightMM" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="0dd749d6-dd72-4084-a238-9eb9388a174b" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="447" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="OUT" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="9f0f9fd3-bf76-4bf2-b227-c6916948fe22" start_index="0" end="0dd749d6-dd72-4084-a238-9eb9388a174b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="04af55dd-337b-463b-9aba-61e204514984" start_index="0" end="9f0f9fd3-bf76-4bf2-b227-c6916948fe22" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fd84fcf1-a670-4cc4-8c18-116aa477c4db" start_index="0" end="9f0f9fd3-bf76-4bf2-b227-c6916948fe22" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="73c980c4-2725-4720-b8ec-23237a0ba9f7" start_index="0" end="9f0f9fd3-bf76-4bf2-b227-c6916948fe22" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="535c5ec0-2055-4d66-951c-f74c3ab13eb5" start_index="0" end="9f0f9fd3-bf76-4bf2-b227-c6916948fe22" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="101bc430-fb48-43f4-acb9-f07f903f227c" start_index="0" end="9f0f9fd3-bf76-4bf2-b227-c6916948fe22" end_index="4" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-31.8995856113879" eyeY="34.5578844123369" eyeZ="154.181330455041" lookX="31.8995856113879" lookY="-34.5578844123369" lookZ="-154.181330455041" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>