<Workspace Version="1.2.1.3083" X="94.6666666666665" Y="226" zoom="1" Name="Reload Revit Links by Instance" Description="" ID="d0fd3294-dd8f-4248-947d-59fed43f194a" Category="Bakery.Revit.Document.Links">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="63e2fdf2-9d88-4738-9e8e-a35527c93a58" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#python nodes in dynamo 1.0.0
#created by Nicklas Ã˜stertgaard  nvo@bimshark.com / nvo@shl.fk
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument
collector = Autodesk.Revit.DB.FilteredElementCollector(doc)
#linkInstances = collector.OfClass(Autodesk.Revit.DB.RevitLinkInstance)
linkInstances = IN[0]
successlist = []

for i in linkInstances:
	RevitLinkType  = doc.GetElement(i.GetTypeId())
	try:
		RevitLinkType.Load();
		successlist.append(i)
	except:
		successlist.append("Failure")

OUT= successlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="4a7f0396-1c06-4879-b6f0-4e1e85271e84" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="link instances" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="d38bd5cc-d5e2-4c41-a1ae-a3a42b646143" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="447" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="instanceOrFail" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="07d6f179-6c7b-4daf-b927-5ae0e44a37d6" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="TurnIntoList" x="177" y="158" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="TurnIntoList" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="unknownItem" />
      </Inputs>
      <Outputs>
        <Output value="seq" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="63e2fdf2-9d88-4738-9e8e-a35527c93a58" start_index="0" end="d38bd5cc-d5e2-4c41-a1ae-a3a42b646143" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4a7f0396-1c06-4879-b6f0-4e1e85271e84" start_index="0" end="07d6f179-6c7b-4daf-b927-5ae0e44a37d6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="07d6f179-6c7b-4daf-b927-5ae0e44a37d6" start_index="0" end="63e2fdf2-9d88-4738-9e8e-a35527c93a58" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>