<Workspace Version="1.3.3.4651" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Remove Trailing Double Quote if Present" Description="" ID="b3616fb4-dbde-4cb4-9405-dfb282d37f53" Category="Bakery.Core.String">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="34500dc8-902a-4734-a133-b83aa1d8ca37" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
somethings = IN[0]
strings = []
for x in somethings:
	strings.append(str(x))
newstr = []
lens=[]
for s in strings:
	lens.append(len(s))
	if s[(len(s)-1)]=='"':
		endlen=(len(s)-1)
		temp=s[0:endlen]
		newstr.append(temp)
	else:
		newstr.append(s)

#Assign your output to the OUT variable.
OUT = newstr</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3f54885c-87b0-4186-a98f-0b6de9f9add1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="listOfStrings" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="7c03cf8a-7340-419a-a7b7-947649105588" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="newStrings" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="34500dc8-902a-4734-a133-b83aa1d8ca37" start_index="0" end="7c03cf8a-7340-419a-a7b7-947649105588" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3f54885c-87b0-4186-a98f-0b6de9f9add1" start_index="0" end="34500dc8-902a-4734-a133-b83aa1d8ca37" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>