<Workspace Version="1.0.0.1180" X="-231.46802832419" Y="52.7915934777796" zoom="0.789161032924816" Name="Springs.Beams.FixExtents" Description="Detects all beams from the input list with broken extents(actual length - cut length &lt;  margin) and attemts to correct them." ID="7ae83d0d-faed-43ba-ae85-fdd942b47e2d" Category="Springs.Revit.Utility">
  <NamespaceResolutionMap>
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="ecc1645e-4fab-457f-9d22-4f638da88831" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="600.082862215375" y="12.169730206782" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="def filter1(l1:var[], margin)&#xA;{&#xA;test1 = (l1[0] &gt; l1[1] ? l1[0] - l1[1] : l1[1] - l1[0]);&#xA;return = test1 &gt; margin;&#xA;};" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="1383d6d7-f3f2-466e-b87d-07fb6c8c99cd" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="612.745923040193" y="148.40692552161" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="len1 = str1&lt;1&gt;.GetParameterValueByName(&#xA;{&quot;Length&quot;,&quot;Cut Length&quot;}&lt;2&gt;);&#xA;mask1 = filter1(len1, margin);&#xA;List.FilterByBoolMask(str1,mask1)[&quot;in&quot;];" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="6826ab31-96ff-4e52-8ee9-78f3a09e8d49" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1070.70821445363" y="193.232492528571" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright(c) 2015, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com

import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import ElementId
from Autodesk.Revit.DB.Structure import StructuralFramingUtils

clr.AddReference("System")
from System.Collections.Generic import List as cList

def tolist(obj1):
	if hasattr(obj1,"__iter__"):
		return obj1
	else:
		return [obj1]

beams = UnwrapElement(tolist(IN[0]))

TransactionManager.Instance.EnsureInTransaction(doc)
for b in beams:
	try:
		StructuralFramingUtils.DisallowJoinAtEnd(b,0)
		StructuralFramingUtils.DisallowJoinAtEnd(b,1)
	except:
		pass
		
ids1 = [e.Id for e in beams]
ids2 = cList[ElementId](ids1)
uidoc.Selection.SetElementIds(ids2)
OUT = "%s beams corrected in Revit." %ids2.Count
TransactionManager.Instance.TransactionTaskDone()</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="0e242a3e-c651-4aa9-b8ba-d479bb00bc48" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="274.046929822188" y="160.749774280288" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;framing&quot;;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d34959a1-f9bf-4cc7-8831-da399c6b279f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="269.797757484782" y="98.7958483155021" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="beams:var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="52d80ced-cff5-4359-b259-9417e874ffb0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="384.601387171996" y="219.089690317136" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="margin:double = 300" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5b762c6c-eaf4-4b2c-a5ee-bc6d3cf40f64" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1223.79254044128" y="195.695865214954" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="result" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="45a0fb48-d596-4710-aed7-b8e8d978caaa" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Filter.ByClassName" x="428.275063074201" y="101.314726693479" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <ID value="3760b286-a8de-438d-9238-c6755dc9c862" />
      <Name value="Filter.ByClassName" />
      <Description value="Filters a list of objects by the object's class name. Note that Dynamo elements belong to different classes than their Revit counterparts. Use the Object.Class node to check an object's class." />
      <Inputs>
        <Input value="object" />
        <Input value="className" />
      </Inputs>
      <Outputs>
        <Output value="in" />
        <Output value="out" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="1383d6d7-f3f2-466e-b87d-07fb6c8c99cd" start_index="2" end="6826ab31-96ff-4e52-8ee9-78f3a09e8d49" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6826ab31-96ff-4e52-8ee9-78f3a09e8d49" start_index="0" end="5b762c6c-eaf4-4b2c-a5ee-bc6d3cf40f64" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0e242a3e-c651-4aa9-b8ba-d479bb00bc48" start_index="0" end="45a0fb48-d596-4710-aed7-b8e8d978caaa" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d34959a1-f9bf-4cc7-8831-da399c6b279f" start_index="0" end="45a0fb48-d596-4710-aed7-b8e8d978caaa" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="52d80ced-cff5-4359-b259-9417e874ffb0" start_index="0" end="1383d6d7-f3f2-466e-b87d-07fb6c8c99cd" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="45a0fb48-d596-4710-aed7-b8e8d978caaa" start_index="0" end="1383d6d7-f3f2-466e-b87d-07fb6c8c99cd" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>