<Workspace Version="1.0.0.1180" X="107.2" Y="117.6" zoom="1" Name="Springs.Mesh.ToToolkitMesh" Description="Converts a Dynamo mesh to a toolkit mesh. You obviously need to have the appropriate version of the mesh toolkit package downloaded first." ID="d992f1f9-a78e-4864-b50f-92973fe214fe" Category="Springs.Geometry">
  <NamespaceResolutionMap>
    <ClassMap partialName="Surface" resolvedName="Autodesk.DesignScript.Geometry.Surface" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Dynamo.Mesh" resolvedName="Autodesk.Dynamo.MeshToolkit.Mesh" assemblyName="MeshToolkit.dll" />
    <ClassMap partialName="Autodesk.Dynamo.MeshToolkit.Mesh" resolvedName="Autodesk.Dynamo.MeshToolkit.Mesh" assemblyName="MeshToolkit.dll" />
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="8a64e7b6-3c9a-4300-95b0-ffd7e4ca42c2" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="162" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="def Mesh2Mesh(m1){&#xA;vp = m1.VertexPositions;&#xA;fi = m1.FaceIndices;&#xA;fi2 = Flatten(List.Transpose({fi.A,fi.B,fi.C}));&#xA;return = Dynamo.Mesh.ByVerticesAndIndices(vp,fi2);&#xA;};&#xA;Mesh2Mesh(m1);" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="24c2dfa7-f176-46b2-bb37-7aa1e79bdf8b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="mesh:var" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="bc38c9e5-2075-4882-bca1-29a4c1deb11f" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="676.2" y="106.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="toolkitMesh" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="8a64e7b6-3c9a-4300-95b0-ffd7e4ca42c2" start_index="0" end="bc38c9e5-2075-4882-bca1-29a4c1deb11f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="24c2dfa7-f176-46b2-bb37-7aa1e79bdf8b" start_index="0" end="8a64e7b6-3c9a-4300-95b0-ffd7e4ca42c2" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="31160.4344563659" eyeY="86607.3966554698" eyeZ="116270.111861701" lookX="-48311.2955088628" lookY="-51506.8830524174" lookZ="-99446.2303244004" upX="-0.0953217574239409" upY="0.975916720431984" upZ="-0.196214763184763" />
  </Cameras>
</Workspace>