<Workspace Version="0.8.1.1693" X="195.46663506043" Y="392.412670054941" zoom="0.877486844646799" Name="Curve.ClosedLoopThroughPoints" ID="576880d2-5f2c-4e34-9183-359361aaa077" Description="Creates a *closed* loop of curves based on a given list of points" Category="Clockwork.Geometry.Curve.Create">
  <NamespaceResolutionMap>
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Symbol guid="ce17390f-1522-4ac4-b6e6-9152d83e7a97" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="points : Autodesk.Point[]" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="0199b100-662e-48cb-ab5c-f6a4ed55d5cf" type="Dynamo.Nodes.Output" nickname="Output" x="828" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Curves" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.CodeBlockNodeModel guid="aeca9f88-03b8-40c0-af20-332701041fe9" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="324" y="4.21833333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="PolyCurve.ByPoints(plist,true).Curves();" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="ce17390f-1522-4ac4-b6e6-9152d83e7a97" start_index="0" end="aeca9f88-03b8-40c0-af20-332701041fe9" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="aeca9f88-03b8-40c0-af20-332701041fe9" start_index="0" end="0199b100-662e-48cb-ab5c-f6a4ed55d5cf" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
</Workspace>