<Workspace Version="1.0.0.1180" X="0" Y="0" zoom="1" Name="DetailLevel.Fine" Description="Returns the fine detail level" ID="c5a1257f-4c86-4aaf-a267-541995a9e86d" Category="Clockwork.Revit.Elements.DetailLevel">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="21196873-ce22-42b1-98c8-1247999f0f51" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
OUT = ViewDetailLevel.Fine</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="54491841-7e36-4f74-a82e-d627b9f2796a" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="414" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="Fine" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="21196873-ce22-42b1-98c8-1247999f0f51" start_index="0" end="54491841-7e36-4f74-a82e-d627b9f2796a" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>