<Workspace Version="0.8.1.1693" X="30" Y="359.604320640866" zoom="1.39450686641698" Name="UV.ByXY" ID="299c468e-2730-42d1-86a8-9d887b854a41" Description="Creates UVs from the XY components of point coordinates" Category="Clockwork.Geometry.UV.Create">
  <NamespaceResolutionMap>
    <ClassMap partialName="UV" resolvedName="Autodesk.DesignScript.Geometry.UV" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.CodeBlockNodeModel guid="1b82734d-d186-4de6-b6a8-bf571adb38c9" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="315" y="4.21833333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="UV.ByCoordinates(seq.X,seq.Y);" ShouldFocus="false" />
    <Dynamo.Nodes.Symbol guid="db64d030-88cd-4f7e-b904-a7f50e67e125" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="point : Autodesk.Point" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="487cb3e1-ad6a-4ed7-81f3-bb8ae34570c4" type="Dynamo.Nodes.Output" nickname="Output" x="732" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="uv" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="1b82734d-d186-4de6-b6a8-bf571adb38c9" start_index="0" end="487cb3e1-ad6a-4ed7-81f3-bb8ae34570c4" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="db64d030-88cd-4f7e-b904-a7f50e67e125" start_index="0" end="1b82734d-d186-4de6-b6a8-bf571adb38c9" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
</Workspace>