<Workspace Version="1.0.0.1180" X="0" Y="0" zoom="1" Name="Enumerate Text Align Flags" Description="" ID="7acfdef7-a5ac-496d-ba00-b15dcf8c933b" Category="Bakery.Revit.Application.Enums">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="fec53d33-f583-401d-a286-4219f32fa075" type="PythonNodeModels.PythonNode" nickname="Python Script" x="294.8" y="46.7408508873338" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright(c) 2015, Konrad Sobon
# @arch_laboratory, http://archi-lab.net

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
import System

#Assign your output to the OUT variable
OUT = System.Enum.GetValues(TextAlignFlags)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors />
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>