<Workspace Version="1.0.0.1180" X="0" Y="0" zoom="1" Name="Enumerate Worksharing Display Modes for Document" Description="" ID="def12513-7d38-43ba-b0bc-8565d5524652" Category="Bakery.Revit.Application.Enums">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="9fd4253b-a1e8-4964-9ffb-6cd4dc36081f" type="PythonNodeModels.PythonNode" nickname="Python Script" x="10" y="9" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright(c) 2015, Konrad Sobon
# @arch_laboratory, http://archi-lab.net

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
import System

#Assign your output to the OUT variable
OUT = System.Enum.GetValues(WorksharingDisplayMode)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors />
  <Notes />
  <Annotations />
  <Presets />
</Workspace>