<Workspace Version="1.2.1.3083" X="195.333333333333" Y="115.333333333333" zoom="1" Name="LastItem Pythonic" Description="" ID="ba14e292-ccbc-48ca-b95c-a987c6ae7a02" Category="Bakery.Core.List">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="d7d367e1-5ab6-4445-bcb7-ae64050a9176" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN[0]
takeitems = []
for x in dataEnteringNode:
	lastitem=len(x)-1
	takeitems.append(x[lastitem])

#Assign your output to the OUT variable.
OUT = takeitems</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="72bd1baf-296d-4fb2-bb28-0989c874cb25" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="listOfLists" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="2b25639f-de92-45d0-986d-89b4074ebf71" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="446.333333333333" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="lastitems" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d7d367e1-5ab6-4445-bcb7-ae64050a9176" start_index="0" end="2b25639f-de92-45d0-986d-89b4074ebf71" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="72bd1baf-296d-4fb2-bb28-0989c874cb25" start_index="0" end="d7d367e1-5ab6-4445-bcb7-ae64050a9176" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>