<Workspace Version="1.3.4.6666" X="153.559247026272" Y="71.8740861375302" zoom="1.00600419002725" ScaleFactor="1" Name="Mirror an Element" Description="using python" ID="888c2901-ed8c-4bb1-a658-7749481fe527" Category="Bakery.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="090f06d1-590a-4bf4-b0c4-838948577fb5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="10" y="9.99999999999999" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="elementList" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="19c51152-2e8c-4390-8375-4c6783c86ed0" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="863.312012480499" y="130.918876755071" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Out" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="361438f6-f24c-4f93-8130-6dd2d0ffb8ab" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-12.3624651501431" y="235.762706738009" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="planeList" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="0f78a55e-27c6-4399-a9f5-4096d2b58db5" type="PythonNodeModels.PythonNode" nickname="Python Script" x="468.627027250214" y="76.6655990372973" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

walls = UnwrapElement(IN[0])
planes = IN[1]
rvt_planes =list()
mirrored = list()
count = 0

def Dyn2RvtPlane(pl1):
	normal1 = pl1.Normal.ToXyz(True)
	origin1 = pl1.Origin.ToXyz(True)
	return Autodesk.Revit.DB.Plane.CreateByNormalAndOrigin(normal1, origin1)

TransactionManager.Instance.EnsureInTransaction(doc)
for p in planes:
	rvt_planes.append(Dyn2RvtPlane(p))
for w, rp in zip(walls, rvt_planes):
	try:
#		item.Flip()
		ElementTransformUtils.MirrorElement(doc, w.Id, rp)
		count += 1
	except:
		count += 0
TransactionManager.Instance.TransactionTaskDone()
		
OUT = "%s elements mirrored" %count</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="090f06d1-590a-4bf4-b0c4-838948577fb5" start_index="0" end="0f78a55e-27c6-4399-a9f5-4096d2b58db5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="361438f6-f24c-4f93-8130-6dd2d0ffb8ab" start_index="0" end="0f78a55e-27c6-4399-a9f5-4096d2b58db5" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0f78a55e-27c6-4399-a9f5-4096d2b58db5" start_index="0" end="19c51152-2e8c-4390-8375-4c6783c86ed0" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>