<Workspace Version="1.3.3.4651" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Remove Leading Double Quote if Present" Description="" ID="db188d78-0c41-46f4-97d9-2117b0fac8d6" Category="Bakery.Core.String">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="e6eb26ae-df5f-4590-85a1-03e63211552d" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
somethings = IN[0]
strings = []
for x in somethings:
	strings.append(str(x))
newstr = []
lens=[]
for s in strings:
	if s[0]=='"':
		endlen=(len(s))
		temp=s[1:endlen]
		newstr.append(temp)
	else:
		newstr.append(s)

#Assign your output to the OUT variable.
OUT = newstr</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f35733c0-91f4-43a4-a2f9-3076664fa9eb" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="listOfStrings" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="26704b9b-7dcd-42d4-987f-a39fd124ef0d" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="newList" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e6eb26ae-df5f-4590-85a1-03e63211552d" start_index="0" end="26704b9b-7dcd-42d4-987f-a39fd124ef0d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f35733c0-91f4-43a4-a2f9-3076664fa9eb" start_index="0" end="e6eb26ae-df5f-4590-85a1-03e63211552d" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>