<Workspace Version="1.3.3.4651" X="210.39231837908" Y="254.910309996291" zoom="0.97676875" ScaleFactor="1" Name="Set Workset for a Single Element" Description="use with list.map" ID="64aedabf-9c97-4b48-a69e-3b13c88e0be9" Category="Bakery.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="08e380f9-f646-48fa-b934-8bee1e0dd057" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="10" y="21.3651864801865" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Elementz" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="efb743cc-9e82-482f-8219-ad1e6c45df4b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="100.793282275101" y="142.762744272624" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Worksetz" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="781165eb-acac-4fea-901f-20d727e6252b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="380.352568401889" y="35.0280631184028" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

faminsts = UnwrapElement(IN[0])
ws = UnwrapElement(IN[1])
wsId = ws.Id.IntegerValue
diditwork = ""
try:
	try:
		TransactionManager.Instance.ForceCloseTransaction()
	except:
		pass
	t = Transaction(doc, 'Setting value')
	t.Start()
	wsparam = faminsts.get_Parameter(BuiltInParameter.ELEM_PARTITION_PARAM)
	wsparamAsInt = wsparam.AsInteger()
	wsparam.Set(wsId)
	t.Commit
	diditwork = "Success"
except:
	diditwork = "Failed"
OUT = faminsts, ws, wsId, wsparam, wsparamAsInt, diditwork</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5f3fac0a-f1b8-4a4c-9e65-73fe0c5cfadd" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="815.972027972028" y="10" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="ChangedElems" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="08e380f9-f646-48fa-b934-8bee1e0dd057" start_index="0" end="781165eb-acac-4fea-901f-20d727e6252b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="efb743cc-9e82-482f-8219-ad1e6c45df4b" start_index="0" end="781165eb-acac-4fea-901f-20d727e6252b" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="781165eb-acac-4fea-901f-20d727e6252b" start_index="0" end="5f3fac0a-f1b8-4a4c-9e65-73fe0c5cfadd" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>