<Workspace Version="0.9.1.4062" X="0" Y="0" zoom="1" Name="Flat List to List of Strings" Description="using python methods" ID="82b8a446-c4a1-4d64-8736-01c0b01ae798" Category="Bakery.Core.List">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="ac91d8c7-c565-48ff-9a5c-c7307d07c25f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="562" y="427.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <Symbol value="Original List" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e1b164ff-d2f3-4075-88ef-34f40795eca6" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1011" y="394.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false">
      <Symbol value="List of Strings" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="597954f1-62f9-48cf-b313-ccdfeca220a4" type="PythonNodeModels.PythonNode" nickname="Python Script" x="766" y="349.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

stringList = []
for x in dataEnteringNode[0]:
	try:
		tempString = str(x)
	except:
		tempString = "stringConversionFailed"
	stringList.append(tempString)
#Assign your output to the OUT variable
OUT = stringList</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ac91d8c7-c565-48ff-9a5c-c7307d07c25f" start_index="0" end="597954f1-62f9-48cf-b313-ccdfeca220a4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="597954f1-62f9-48cf-b313-ccdfeca220a4" start_index="0" end="e1b164ff-d2f3-4075-88ef-34f40795eca6" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>