<Workspace Version="1.1.0.2065" X="-369.216812992238" Y="-0.10781473143777" zoom="0.954042924882813" Name="CurtainGrid.SkippedSegmentCurves" Description="Retrieve all the removed segment curves of the grid line. " ID="fb7c31f4-9e87-42ab-bd37-b581bcc44fc0" Category="Rhythm.Revit.Elements.CurtainGrid">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="40941fe4-2169-4dd7-bc46-aba999a6f412" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1746.66462239842" y="340.139973310979" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="skippedSegmentCurves" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9764be15-42ba-48e2-9615-d75a9350db52" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Chop" x="1437.80430211545" y="377.780916665892" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.List.Chop@var[]..[],int[]" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="f752a43e-b645-4ad0-b2ec-76ea81e5db75" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="List.Chop" x="1609.6786973965" y="417.972612249002" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="DSCoreNodes.dll" function="DSCore.List.Chop@var[]..[],int[]" />
    <PythonNodeModels.PythonNode guid="7e8d3190-5f8a-4e2d-a70b-02e1a4963d87" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1185.28311603814" y="307.800412254212" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
curves = UnwrapElement(IN[0])
elementlist = []

TransactionManager.Instance.EnsureInTransaction(doc)
for curve in curves:
	revitCurves = curve.ToProtoType()
	elementlist.append(revitCurves)
TransactionManager.Instance.TransactionTaskDone()
OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="236790cb-6905-4486-8177-11f92d6f11f3" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Count" x="1215.65637448292" y="408.903090102332" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Count@var[]..[]" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="90ad51dd-439e-431a-9d64-1caa270f8bbd" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Count" x="1220.46441109212" y="497.353055286132" isVisible="true" isUpstreamVisible="true" lacing="Longest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Count@var[]..[]" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="480c7930-2c3a-44b2-96c0-34dfd9149330" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="939.358808661901" y="308.117081275522" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="93348142-2d15-4b80-9741-d003858d4e7c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="775.108631354651" y="305.848853782622" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

#unwrap all elements to use with API
items = UnwrapElement(IN[0])

#apply API method to list
typelist = list()
for i in items:
	try:
		typelist.append(i.SkippedSegmentCurves)
	except:
		typelist.append(list())


#Assign your output to the OUT variable
OUT = typelist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="ab65040e-fbd8-43af-8bda-20b6dc9d4ace" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="530.707545758373" y="307.826511601532" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="4a9e4dc4-1091-44e5-acd1-6977df265cc5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="392.907880911481" y="304.829125373951" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="curtainGrid" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="9764be15-42ba-48e2-9615-d75a9350db52" start_index="0" end="f752a43e-b645-4ad0-b2ec-76ea81e5db75" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f752a43e-b645-4ad0-b2ec-76ea81e5db75" start_index="0" end="40941fe4-2169-4dd7-bc46-aba999a6f412" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7e8d3190-5f8a-4e2d-a70b-02e1a4963d87" start_index="0" end="9764be15-42ba-48e2-9615-d75a9350db52" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="236790cb-6905-4486-8177-11f92d6f11f3" start_index="0" end="9764be15-42ba-48e2-9615-d75a9350db52" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="90ad51dd-439e-431a-9d64-1caa270f8bbd" start_index="0" end="f752a43e-b645-4ad0-b2ec-76ea81e5db75" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="480c7930-2c3a-44b2-96c0-34dfd9149330" start_index="0" end="7e8d3190-5f8a-4e2d-a70b-02e1a4963d87" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="93348142-2d15-4b80-9741-d003858d4e7c" start_index="0" end="236790cb-6905-4486-8177-11f92d6f11f3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="93348142-2d15-4b80-9741-d003858d4e7c" start_index="0" end="480c7930-2c3a-44b2-96c0-34dfd9149330" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ab65040e-fbd8-43af-8bda-20b6dc9d4ace" start_index="0" end="93348142-2d15-4b80-9741-d003858d4e7c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4a9e4dc4-1091-44e5-acd1-6977df265cc5" start_index="0" end="90ad51dd-439e-431a-9d64-1caa270f8bbd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4a9e4dc4-1091-44e5-acd1-6977df265cc5" start_index="0" end="ab65040e-fbd8-43af-8bda-20b6dc9d4ace" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-31.0782914596038" eyeY="188.103119196707" eyeZ="122.323791071316" lookX="72.9840197102908" lookY="-107.69885975429" lookZ="-136.175284756543" upX="0.180774769316409" upY="0.923879532511288" upZ="-0.337293777270387" />
  </Cameras>
</Workspace>