<Workspace Version="0.9.0.3067" X="-1967.9429467782" Y="-356.356731226236" zoom="1.21969707110707" Name="Geometry.ToRevitType" Description="This will convert designscript geometyr into Revit.DB types. Currently tested with curves, nurbs curves and solids." ID="b9683508-5618-4b16-a101-a95081546193" Category="Rhythm.Geometry.Geometry">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="89d1c015-e532-4fd7-9080-22cc775fb3e4" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2167.0142828619" y="694.552033873904" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
curves = UnwrapElement(IN[0])
elementlist = []

TransactionManager.Instance.EnsureInTransaction(doc)
for curve in curves:
	revitCurves = curve.ToRevitType()
	elementlist.append(revitCurves)
TransactionManager.Instance.TransactionTaskDone()
OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.Output guid="18ac0b83-cc38-41d0-9282-78693e4cf9fd" type="Dynamo.Nodes.Output" nickname="Output" x="2439.57951285671" y="695.90832954129" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="RevitType" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Symbol guid="0f691290-1f3e-4618-b1f6-9cbc5210bff5" type="Dynamo.Nodes.Symbol" nickname="Input" x="1827.58725019128" y="695.258093904027" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="var[]..[]" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.CodeBlockNodeModel guid="8c7f3023-9f9c-4418-b252-07190aeed828" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1945.62672176722" y="694.015059683927" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="Flatten({item});" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="1ae40a40-d7f5-4301-b9c6-e05f62bfc046" type="Dynamo.Nodes.DSFunction" nickname="Flatten" x="2316.01729489157" y="693.0261294339" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="BuiltIn" function="Flatten@var[]..[]" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="89d1c015-e532-4fd7-9080-22cc775fb3e4" start_index="0" end="1ae40a40-d7f5-4301-b9c6-e05f62bfc046" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="0f691290-1f3e-4618-b1f6-9cbc5210bff5" start_index="0" end="8c7f3023-9f9c-4418-b252-07190aeed828" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="8c7f3023-9f9c-4418-b252-07190aeed828" start_index="0" end="89d1c015-e532-4fd7-9080-22cc775fb3e4" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1ae40a40-d7f5-4301-b9c6-e05f62bfc046" start_index="0" end="18ac0b83-cc38-41d0-9282-78693e4cf9fd" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>