<Workspace Version="1.3.0.875" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Enumerate NavisworksCoordinates" Description="for export nwc node&#xD;&#xA;" ID="0a19552e-d48b-417a-9de9-71b7364c9576" Category="Bakery.Construction.Navisworks">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="24631caf-5a6f-428a-b949-9f380835e274" type="PythonNodeModels.PythonNode" nickname="Python Script" x="624.666666666667" y="290.666666666666" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="0">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB import Structure
import System

#Assign your output to the OUT variable
OUT = System.Enum.GetValues(Autodesk.Revit.DB.NavisworksCoordinates)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors />
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>