<Workspace Version="1.2.1.3083" X="-256.955729449643" Y="-62.9620168662424" zoom="1.78359936238281" Name="Enumerate Path Types" Description="" ID="a028d0ae-5a30-4085-a68e-861848658fdb" Category="Bakery.Revit.Application.Enums">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="87ca3965-71f0-4f77-91ba-5014edfd0869" type="PythonNodeModels.PythonNode" nickname="Python Script" x="293.733333333333" y="47.8704254436669" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2015, Konrad Sobon
# @arch_laboratory, http://archi-lab.net

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
import System

#Assign your output to the OUT variable
OUT = System.Enum.GetValues(PathType)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors />
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>