<Workspace Version="1.0.0.1180" X="-487.104621137783" Y="159.9767906496" zoom="1.30764135636719" Name="Get Grid Extents" Description="" ID="81ce76b6-239a-4615-a8cc-796e46a86cd5" Category="Bakery.Revit.Elements">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="12664ff2-ff41-45ec-ba8b-7774d0fcfa5d" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="TurnIntoList" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="TurnIntoList" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="unknownItem" />
      </Inputs>
      <Outputs>
        <Output value="seq" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <PythonNodeModels.PythonNode guid="ec1ffd66-dc5f-406f-b7c8-a1d213f737c6" type="PythonNodeModels.PythonNode" nickname="Python Script" x="441.2" y="19.2000000000001" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#python nodes in dynamo 0.7
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

#unwrap all elements to use with API
elements = []
for i in IN[0]:
	elements.append(UnwrapElement(i))
	
# "Start" the transaction
TransactionManager.Instance.EnsureInTransaction(doc)

outlinelist = list()
for item in elements:
    try:
    	outlinelist.append(item.GetExtents())
    except:
    	outlinelist.append("No outline found")

# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()


#Assign your output to the OUT variable
OUT = outlinelist</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="90ef41f0-f041-413b-b09a-b1bd9763a14c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="681.911533201185" y="299.030664023694" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#python nodes in dynamo 0.7
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#The inputs to this node will be stored as a list in the IN variable.


#unwrap all elements to use with API

outlinelist = IN[0]
# "Start" the transaction
TransactionManager.Instance.EnsureInTransaction(doc)
maxlist = list()
for item in outlinelist:
    try:
    	maxlist.append(item.MaximumPoint)
    except:
    	maxlist.append("Not found")

# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable
OUT = maxlist</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="b5060f98-6406-40bb-9ade-79a8f4bd0564" type="PythonNodeModels.PythonNode" nickname="Python Script" x="761.026865213031" y="143.437177733728" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#python nodes in dynamo 0.7
#proposed by Julien Benoit @jbenoit44 
#http://aecuandme.wordpress.com/
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#The inputs to this node will be stored as a list in the IN variable.


#unwrap all elements to use with API

outlinelist = IN[0]
# "Start" the transaction
TransactionManager.Instance.EnsureInTransaction(doc)
minlist = list()
for item in outlinelist:
    try:
    	minlist.append(item.MinimumPoint)
    except:
    	minlist.append("Not found")

# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable
OUT = minlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f66e646f-b7fc-4fd8-864e-889c75264d4c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="unknownItem : var[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="5ea1b934-ffce-483a-b056-01390a007a08" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="958.426865213031" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="outlineObjects" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="a1095c6f-69e1-4e6e-a1e2-663f6ee75a8b" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="943.226865213031" y="406.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="maximumPointsXYZRevitFeet" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="3ec685c1-f993-48ca-b8c4-db5c4fda7b83" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="958.426865213031" y="300" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="minimumPointsXYZRevitFeet" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="12664ff2-ff41-45ec-ba8b-7774d0fcfa5d" start_index="0" end="ec1ffd66-dc5f-406f-b7c8-a1d213f737c6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ec1ffd66-dc5f-406f-b7c8-a1d213f737c6" start_index="0" end="b5060f98-6406-40bb-9ade-79a8f4bd0564" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ec1ffd66-dc5f-406f-b7c8-a1d213f737c6" start_index="0" end="90ef41f0-f041-413b-b09a-b1bd9763a14c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ec1ffd66-dc5f-406f-b7c8-a1d213f737c6" start_index="0" end="5ea1b934-ffce-483a-b056-01390a007a08" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="90ef41f0-f041-413b-b09a-b1bd9763a14c" start_index="0" end="a1095c6f-69e1-4e6e-a1e2-663f6ee75a8b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b5060f98-6406-40bb-9ade-79a8f4bd0564" start_index="0" end="3ec685c1-f993-48ca-b8c4-db5c4fda7b83" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f66e646f-b7fc-4fd8-864e-889c75264d4c" start_index="0" end="12664ff2-ff41-45ec-ba8b-7774d0fcfa5d" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>