<Workspace Version="0.8.1.1693" X="30" Y="260.767606091718" zoom="1.14681724845996" Name="AngleBisector.ByPoints" ID="277a40e8-4916-4788-9f54-2fc26cb1b7dc" Description="Retrieves the vector of an angle bisector at point B based on three points (A, B, C) that define the angle. " Category="Clockwork.Geometry.Vector.Create">
  <NamespaceResolutionMap>
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Symbol guid="092a3985-496e-47a6-98bd-ab9564e4a9b9" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="PointA : Autodesk.Point" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="d4fb96a1-22b0-4ce3-9290-a122a7b50956" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="167.126666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="PointB : Autodesk.Point" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="68e5be35-e030-4394-b675-d1e86c1d7c42" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="83.5633333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="PointC : Autodesk.Point" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.CodeBlockNodeModel guid="30b8afcd-4400-4a85-af9d-16ea76c78ae0" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="324" y="70.2183333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="plist = {a,c};&#xA;px = Math.Average(plist.X);&#xA;py = Math.Average(plist.Y);&#xA;pz = Math.Average(plist.Z);&#xA;// Find midpoint between points A &amp; C&#xA;midpoint = Autodesk.Point.ByCoordinates(px,py,pz);&#xA;// Create vector between point B &amp; midpoint&#xA;vec = Vector.ByTwoPoints(b,midpoint).Normalized();" ShouldFocus="false" />
    <Dynamo.Nodes.Output guid="f5c7cdf7-e9d9-4cbc-ae84-45d230227152" type="Dynamo.Nodes.Output" nickname="Output" x="899" y="188.943333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Vector" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="092a3985-496e-47a6-98bd-ab9564e4a9b9" start_index="0" end="30b8afcd-4400-4a85-af9d-16ea76c78ae0" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="d4fb96a1-22b0-4ce3-9290-a122a7b50956" start_index="0" end="30b8afcd-4400-4a85-af9d-16ea76c78ae0" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="68e5be35-e030-4394-b675-d1e86c1d7c42" start_index="0" end="30b8afcd-4400-4a85-af9d-16ea76c78ae0" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="30b8afcd-4400-4a85-af9d-16ea76c78ae0" start_index="5" end="f5c7cdf7-e9d9-4cbc-ae84-45d230227152" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
</Workspace>