<Workspace Version="0.8.2.2392" X="30" Y="313.709302325581" zoom="1.4561717352415" Name="Floor.SlabShapeHasBeenModified" Description="Checks if the shape of a floor slab has been modified with the shape editing tools" ID="9eb6949f-375f-493c-ba62-9198c69c249e" Category="Clockwork.Revit.Elements.Floor.Query">
  <NamespaceResolutionMap>
    <ClassMap partialName="Floor" resolvedName="Revit.Elements.Floor" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Function guid="eedb1efd-0971-449d-960e-6bf5ea064cbc" type="Dynamo.Nodes.Function" nickname="Roof.SlabShapeHasBeenModified" x="175" y="0" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False">
      <ID value="5522a73c-f9bd-45b1-a63b-5c2262fe1f98" />
      <Name value="Roof.SlabShapeHasBeenModified" />
      <Description value="Checks if the shape of a roof slab has been modified with the shape editing tools" />
      <Inputs>
        <Input value="roof" />
      </Inputs>
      <Outputs>
        <Output value="bool" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Symbol guid="7b0b7ffe-62d8-4bab-937c-cfb11b96881b" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="floor" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="a568c430-d2b3-4532-9e8a-3f10c1d3abe2" type="Dynamo.Nodes.Output" nickname="Output" x="493" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="bool" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="eedb1efd-0971-449d-960e-6bf5ea064cbc" start_index="0" end="a568c430-d2b3-4532-9e8a-3f10c1d3abe2" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="7b0b7ffe-62d8-4bab-937c-cfb11b96881b" start_index="0" end="eedb1efd-0971-449d-960e-6bf5ea064cbc" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>