<Workspace Version="1.0.0.1180" X="214.413443777226" Y="145.553399941166" zoom="0.899691736191744" Name="ModelCurve.Type" Description="Gets the type of a given model curve" ID="c7d59894-4fec-48c7-9ff1-3912148225ef" Category="Clockwork.Revit.Elements.ModelCurve.Query">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="6eaa085b-17a4-441e-964c-b7dd23aa07f0" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="TurnIntoList" x="-33.6387063514204" y="162.766409334636" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="Turn Into List" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="unknownItem" />
      </Inputs>
      <Outputs>
        <Output value="seq" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7d675e6f-ff05-4b4b-89eb-be20b050e79e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-210" y="95.7142857142857" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="modelCurve" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="f6657b38-376f-4e7b-9fb8-9538314be35d" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="580.662742592044" y="93.4194555121572" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="type" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="e8916af6-0865-4083-8b19-a04de06ed944" type="PythonNodeModels.PythonNode" nickname="Python Script" x="147.891783062879" y="160.230679850638" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

items = UnwrapElement(IN[0])
typelist = list()
for item in items:	
	try: 
		typelist.append(item.CurveElementType)
	except:
		typelist.append(list())
OUT = typelist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="4e4c71b9-7dea-4a8e-9d1e-6eb2646caf3a" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="ReturnListOrSingleValue" x="334.377070982209" y="94.5135655141125" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <ID value="44ac4888-4aa4-49a9-9344-23b729c11df9" />
      <Name value="ReturnListOrSingleValue" />
      <Description value="If the item in input #1 is not a list, only the first item of the list in input #2 will be returned." />
      <Inputs>
        <Input value="unknownItem" />
        <Input value="seq" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6eaa085b-17a4-441e-964c-b7dd23aa07f0" start_index="0" end="e8916af6-0865-4083-8b19-a04de06ed944" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7d675e6f-ff05-4b4b-89eb-be20b050e79e" start_index="0" end="6eaa085b-17a4-441e-964c-b7dd23aa07f0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7d675e6f-ff05-4b4b-89eb-be20b050e79e" start_index="0" end="4e4c71b9-7dea-4a8e-9d1e-6eb2646caf3a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e8916af6-0865-4083-8b19-a04de06ed944" start_index="0" end="4e4c71b9-7dea-4a8e-9d1e-6eb2646caf3a" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4e4c71b9-7dea-4a8e-9d1e-6eb2646caf3a" start_index="0" end="f6657b38-376f-4e7b-9fb8-9538314be35d" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="253.407241821289" eyeY="67.8294830322266" eyeZ="251.54655456543" lookX="-282.658386230469" lookY="-97.0411529541016" lookZ="-251.745376586914" upX="-0.0260616019368172" upY="0.999390840530396" upZ="-0.0232113692909479" />
  </Cameras>
</Workspace>