<Workspace Version="0.8.2.2392" X="30" Y="388.916445783133" zoom="1.41867469879518" Name="Plane.ByBestFitFromFace" Description="Creates a plane from face" ID="31a34783-93cd-4d65-8500-66885bf5a65b" Category="Clockwork.Geometry.Plane.Create">
  <NamespaceResolutionMap>
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Surface" resolvedName="Autodesk.DesignScript.Geometry.Surface" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Symbol guid="04153f83-f5c1-412a-b148-af1dcbe329bd" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="surface : Surface" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="05b01b23-a1f9-4a05-b5d3-703a5315cfbf" type="Dynamo.Nodes.Output" nickname="Output" x="925" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="plane" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.CodeBlockNodeModel guid="ff25d4c3-5f2b-4b6f-911c-8d4ccd537ef8" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="274" y="4.21333333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="Plane.ByBestFitThroughPoints(surf.Vertices.PointGeometry);" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="04153f83-f5c1-412a-b148-af1dcbe329bd" start_index="0" end="ff25d4c3-5f2b-4b6f-911c-8d4ccd537ef8" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ff25d4c3-5f2b-4b6f-911c-8d4ccd537ef8" start_index="0" end="05b01b23-a1f9-4a05-b5d3-703a5315cfbf" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>