<Workspace Version="0.8.2.2392" X="30" Y="202.478606856309" zoom="0.890590809628009" Name="Point.CentralProjectionOnFace" Description="Projects a list of points onto a given face" ID="4776f465-5705-4468-84f1-ab1f2636918a" Category="Clockwork.Geometry.Point.Actions">
  <NamespaceResolutionMap>
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Surface" resolvedName="Autodesk.DesignScript.Geometry.Surface" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Symbol guid="ffcf7dc2-7ded-433a-b258-b3e1105d0165" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="centralProjectionPoint : Autodesk.Point" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="61911a8b-9f4b-48f1-b413-13e8380fc47a" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="83.5633333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="projectionPoints : Autodesk.Point[]" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="3867d9ab-b793-4452-9d8e-031f35965438" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="167.126666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="surface : Surface" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="d8ace574-8625-4e35-af8a-caf356dd2d27" type="Dynamo.Nodes.Output" nickname="Output" x="1037.88697788698" y="94.7918345618345" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="projectedPoints" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.CodeBlockNodeModel guid="53e77dd8-03db-435b-a30c-cba5653b8db0" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="527.886977886978" y="81.4468345618345" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="dir = Vector.ByTwoPoints(center,plist);&#xA;surf.ProjectInputOnto(plist,dir);" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="ffcf7dc2-7ded-433a-b258-b3e1105d0165" start_index="0" end="53e77dd8-03db-435b-a30c-cba5653b8db0" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="61911a8b-9f4b-48f1-b413-13e8380fc47a" start_index="0" end="53e77dd8-03db-435b-a30c-cba5653b8db0" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="3867d9ab-b793-4452-9d8e-031f35965438" start_index="0" end="53e77dd8-03db-435b-a30c-cba5653b8db0" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="53e77dd8-03db-435b-a30c-cba5653b8db0" start_index="1" end="d8ace574-8625-4e35-af8a-caf356dd2d27" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="72.3681498179245" eyeY="24.897663660627" eyeZ="8.88569149874949" lookX="-72.3681498179245" lookY="-19.897663660627" lookZ="-8.88569149874949" />
  </Cameras>
</Workspace>