<Workspace Version="0.8.2.2392" X="207.933588143526" Y="395.487548678822" zoom="1.12844270833334" Name="Room.IsPointInside" Description="Evaluates if a ponti is located inside a given room." ID="46d97eca-f979-492a-bb58-8545a2425e6f" Category="Clockwork.Revit.Elements.Room.Query">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Symbol guid="187de382-0c2f-494a-be7e-1e71e5a7991a" type="Dynamo.Nodes.Symbol" nickname="Input" x="5.24180967238692" y="-59.4063962558503" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="room" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="33aa457e-d78c-447b-a7ef-361bb1d32c07" type="Dynamo.Nodes.Output" nickname="Output" x="870.03744149766" y="-57.6552262090483" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="bool" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Symbol guid="32029b7a-e637-4eee-8e0b-85d67cfe2f6c" type="Dynamo.Nodes.Symbol" nickname="Input" x="-104.836193447738" y="84.2511700468019" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="point : Autodesk.Point" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Function guid="04dbea93-ca6f-4530-8a04-a26466615b80" type="Dynamo.Nodes.Function" nickname="ReturnListOrSingleValue" x="578.03744149766" y="-57.6552262090483" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <ID value="44ac4888-4aa4-49a9-9344-23b729c11df9" />
      <Name value="ReturnListOrSingleValue" />
      <Description value="If the item in input #1 is not a list, only the first item of the list in input #2 will be returned." />
      <Inputs>
        <Input value="unknownItem" />
        <Input value="seq" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <DSIronPythonNode.PythonNode guid="6c1c4ee5-a7ed-44b8-aa57-2d7cb3cb5ffb" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="378" y="29" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="2">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

rooms = UnwrapElement(IN[0])
points = [x.ToXyz() for x in IN[1]]
roomlist = list()
for point in points:
	booleans = list()
	for room in rooms:
		try:
			if room.IsPointInRoom(point):
				booleans.append(True)
			else:
				booleans.append(False)
		except:
			booleans.append(False)
	roomlist.append(booleans)
OUT = roomlist</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Function guid="639aec4f-18df-4d66-bbb4-2258d05b3a15" type="Dynamo.Nodes.Function" nickname="Turn Into List" x="173" y="84" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="Turn Into List" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="" />
      </Inputs>
      <Outputs>
        <Output value="seq" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Function guid="e248988d-6f28-4e7b-9d08-ebe46ff58d0b" type="Dynamo.Nodes.Function" nickname="Turn Into List" x="173" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="Turn Into List" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="" />
      </Inputs>
      <Outputs>
        <Output value="seq" />
      </Outputs>
    </Dynamo.Nodes.Function>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="187de382-0c2f-494a-be7e-1e71e5a7991a" start_index="0" end="e248988d-6f28-4e7b-9d08-ebe46ff58d0b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="187de382-0c2f-494a-be7e-1e71e5a7991a" start_index="0" end="04dbea93-ca6f-4530-8a04-a26466615b80" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="32029b7a-e637-4eee-8e0b-85d67cfe2f6c" start_index="0" end="639aec4f-18df-4d66-bbb4-2258d05b3a15" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="04dbea93-ca6f-4530-8a04-a26466615b80" start_index="0" end="33aa457e-d78c-447b-a7ef-361bb1d32c07" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="6c1c4ee5-a7ed-44b8-aa57-2d7cb3cb5ffb" start_index="0" end="04dbea93-ca6f-4530-8a04-a26466615b80" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="639aec4f-18df-4d66-bbb4-2258d05b3a15" start_index="0" end="6c1c4ee5-a7ed-44b8-aa57-2d7cb3cb5ffb" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="e248988d-6f28-4e7b-9d08-ebe46ff58d0b" start_index="0" end="6c1c4ee5-a7ed-44b8-aa57-2d7cb3cb5ffb" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>