<Workspace Version="1.0.0.1180" X="-195.806379750084" Y="22.983582191364" zoom="1.1113575327695" Name="SpotElevation.ByFloorPlanAndPoint" Description="Places a spot elevation at a given point in a given floor plan." ID="89e68d5c-018d-4aba-9d03-a5079b957162" Category="Clockwork.Revit.Elements.SpotElevation.Create">
  <NamespaceResolutionMap>
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="FloorPlanView" resolvedName="Revit.Elements.Views.FloorPlanView" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="ce1b75de-eff5-4540-a0aa-571ace531dbd" type="PythonNodeModels.PythonNode" nickname="Python Script" x="850.882073635981" y="280.338171904393" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="7">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
views = UnwrapElement(IN[0])
pts = UnwrapElement(IN[1])
bend = UnwrapElement(IN[2])
end = UnwrapElement(IN[3])
leader = UnwrapElement(IN[4])
isoview = UnwrapElement(IN[5])
intsecvec = UnwrapElement(IN[6])
elementlist = []

i = 0;
TransactionManager.Instance.EnsureInTransaction(doc)
for pt in pts:
	view = views[i]
	pt = pt.ToXyz()
	refintsec = ReferenceIntersector(isoview)
	refintsec.TargetType = FindReferenceTarget.Face
	ref = refintsec.FindNearest(pt,intsecvec[i].AsPoint().ToXyz()).GetReference()
	elementlist.append(doc.Create.NewSpotElevation(view, ref, pt, pt.Add(bend.AsPoint().ToXyz()), pt.Add(end.AsPoint().ToXyz()), pt, leader))
	i += 1
TransactionManager.Instance.TransactionTaskDone()

OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="9e38c952-8211-4f15-a1f0-4550b026b137" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Document.Default3DView" x="515.882073635981" y="496.338171904393" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="True" />
      <ID value="ef9e6b6f-d604-43d4-85f8-825a7c7c6303" />
      <Name value="Document.Default3DView" />
      <Description value="Returns the default view of the current model (if there is such a view)" />
      <Inputs>
        <Input value="toggle" />
      </Inputs>
      <Outputs>
        <Output value="view" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a9607fcb-7b4a-4cca-a492-191ebc91d0bf" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.Reverse" x="515.882073635981" y="604.338171904393" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.Reverse" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="d53eb7a5-6426-4442-a899-f7769e24d014" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="View.Direction" x="271.882073635981" y="604.338171904393" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <ID value="07195267-53da-4fa3-8410-62807cdbab46" />
      <Name value="View.Direction" />
      <Description value="Returns the direction of a view" />
      <Inputs>
        <Input value="view" />
      </Inputs>
      <Outputs>
        <Output value="vector" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="b40d16cf-b51d-4674-aae0-5012250e3087" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="TurnIntoList" x="515.882073635981" y="138.338171904393" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="TurnIntoList" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="unknownItem" />
      </Inputs>
      <Outputs>
        <Output value="seq" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="e77db831-6342-4d9c-a00e-7f016442d440" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="TurnIntoList" x="8.88207363598053" y="442.338171904393" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="TurnIntoList" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="unknownItem" />
      </Inputs>
      <Outputs>
        <Output value="seq" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6c8d73d2-00bd-4ff0-9fed-945bce2bf038" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="271.882073635981" y="138.338171904393" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="point : Point" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="837b826c-3643-4cfb-a24d-35d506d939da" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-334.117926364019" y="442.338171904393" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="floorPlan : FloorPlanView" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="7b41a903-1b47-4ad9-9c72-3090451188bb" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1072.88207363598" y="280.338171904393" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="spotElevation" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="529eb314-fdb1-4f99-840c-6db176c4f10a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="515.882073635981" y="246.338171904393" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="bend : Vector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1313106f-226b-401d-8317-a96874bd75d3" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="515.882073635981" y="329.338171904393" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="end : Vector" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="ffae3364-f58e-4cba-89f0-4614f1724072" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="515.882073635981" y="413.338171904393" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="hasLeader : bool = false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ce1b75de-eff5-4540-a0aa-571ace531dbd" start_index="0" end="7b41a903-1b47-4ad9-9c72-3090451188bb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9e38c952-8211-4f15-a1f0-4550b026b137" start_index="0" end="ce1b75de-eff5-4540-a0aa-571ace531dbd" end_index="5" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a9607fcb-7b4a-4cca-a492-191ebc91d0bf" start_index="0" end="ce1b75de-eff5-4540-a0aa-571ace531dbd" end_index="6" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d53eb7a5-6426-4442-a899-f7769e24d014" start_index="0" end="a9607fcb-7b4a-4cca-a492-191ebc91d0bf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b40d16cf-b51d-4674-aae0-5012250e3087" start_index="0" end="ce1b75de-eff5-4540-a0aa-571ace531dbd" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e77db831-6342-4d9c-a00e-7f016442d440" start_index="0" end="ce1b75de-eff5-4540-a0aa-571ace531dbd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e77db831-6342-4d9c-a00e-7f016442d440" start_index="0" end="d53eb7a5-6426-4442-a899-f7769e24d014" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6c8d73d2-00bd-4ff0-9fed-945bce2bf038" start_index="0" end="b40d16cf-b51d-4674-aae0-5012250e3087" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="837b826c-3643-4cfb-a24d-35d506d939da" start_index="0" end="e77db831-6342-4d9c-a00e-7f016442d440" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="529eb314-fdb1-4f99-840c-6db176c4f10a" start_index="0" end="ce1b75de-eff5-4540-a0aa-571ace531dbd" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1313106f-226b-401d-8317-a96874bd75d3" start_index="0" end="ce1b75de-eff5-4540-a0aa-571ace531dbd" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ffae3364-f58e-4cba-89f0-4614f1724072" start_index="0" end="ce1b75de-eff5-4540-a0aa-571ace531dbd" end_index="4" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>