<Workspace Version="1.0.0.1180" X="141.556868490279" Y="247.08097495558" zoom="1.01763151154156" Name="Subcategory.ByName" Description="Creates a new subcategory for a given element category in a *family document* (unless a subcategory of that name already exists - in that case it returns the existing subcategory)" ID="c228eea3-78a1-4aca-8fab-8678c97f17c0" Category="Clockwork.Revit.Elements.Subcategory.Create">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d6d71d1f-01c6-41d4-b96d-c508f552dfe6" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="category" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f7e2d305-757e-4518-af0c-2158ef95c640" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="84" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="name : string" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="bbf8d8cc-b3aa-492f-ba7f-c4d5c2147b92" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="414" y="29" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="subCategory" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="3742c319-ecdb-4cb0-8967-4dda730c28f1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="190" y="29" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
cat = UnwrapElement(IN[0])
subcatname = IN[1]

try:
	subcat = cat.SubCategories.get_Item(subcatname)
except:
	TransactionManager.Instance.EnsureInTransaction(doc)
	subcat = doc.Settings.Categories.NewSubcategory(cat, subcatname)
	TransactionManager.Instance.TransactionTaskDone()
OUT = Revit.Elements.Category.ById(subcat.Id.IntegerValue)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d6d71d1f-01c6-41d4-b96d-c508f552dfe6" start_index="0" end="3742c319-ecdb-4cb0-8967-4dda730c28f1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f7e2d305-757e-4518-af0c-2158ef95c640" start_index="0" end="3742c319-ecdb-4cb0-8967-4dda730c28f1" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3742c319-ecdb-4cb0-8967-4dda730c28f1" start_index="0" end="bbf8d8cc-b3aa-492f-ba7f-c4d5c2147b92" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>