<Workspace Version="0.8.1.1693" X="30" Y="373.909336580087" zoom="0.725324675324675" Name="UV.ConvexHull2D" ID="134846f2-02c9-40ce-8852-8d3146d8cc20" Description="Computes the convex hull of a given set of UV coordinates based on the monotone chain algorithm" Category="Clockwork.Geometry.UV.Actions">
  <NamespaceResolutionMap>
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="UV" resolvedName="Autodesk.DesignScript.Geometry.UV" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Symbol guid="dfdada04-0316-432d-bfd5-d4555a03acd4" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="UVs : UV[]" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="87a8db17-8fc7-4a9c-86aa-308f432fbbec" type="Dynamo.Nodes.Output" nickname="Output" x="1474" y="17.5633333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="UVs" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.CodeBlockNodeModel guid="49ca8a25-29cb-42d6-96d6-c1463dcbbda5" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="941" y="4.21833333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="chains = List.Transpose(chainpoints);&#xA;UV.ByCoordinates(chains[0],chains[1]);" ShouldFocus="false" />
    <DSIronPythonNode.PythonNode guid="e8716f22-4274-4547-b2a7-f0d33c141058" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="717" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="1">
      <Script>import clr

# based on a script found here:
# http://en.wikibooks.org/wiki/Algorithm_Implementation/Geometry/Convex_hull/Monotone_chain#Python

points = IN[0]
#reformat points list
newpoints = list()
for pair in points:
	newpoint = (pair[0],pair[1])
	newpoints.append(newpoint)
points = sorted(set(newpoints))

def cross(o, a, b):
	return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])
 
if len(points) &lt;= 1:
	OUT = points
else:
	lower = []
	for p in points:
		while len(lower) &gt;= 2 and cross(lower[-2], lower[-1], p) &lt;= 0:
			lower.pop()
		lower.append(p)
	upper = []
	for p in reversed(points):
		while len(upper) &gt;= 2 and cross(upper[-2], upper[-1], p) &lt;= 0:
			upper.pop()
		upper.append(p)
	OUT = lower[:-1] + upper[:-1]</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.CodeBlockNodeModel guid="b288a36b-3a35-420f-8a70-cc0233f836d3" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="216" y="4.21833333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="List.Transpose({uvlist1.U,uvlist1.V});" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="dfdada04-0316-432d-bfd5-d4555a03acd4" start_index="0" end="b288a36b-3a35-420f-8a70-cc0233f836d3" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="49ca8a25-29cb-42d6-96d6-c1463dcbbda5" start_index="1" end="87a8db17-8fc7-4a9c-86aa-308f432fbbec" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="e8716f22-4274-4547-b2a7-f0d33c141058" start_index="0" end="49ca8a25-29cb-42d6-96d6-c1463dcbbda5" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="b288a36b-3a35-420f-8a70-cc0233f836d3" start_index="0" end="e8716f22-4274-4547-b2a7-f0d33c141058" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
</Workspace>