<Workspace Version="0.8.1.1693" X="30" Y="208.244330104923" zoom="1.47699757869249" Name="Vector.XAxisNegative" ID="d7173a2c-acdd-452e-acb6-3bd0e12c9037" Description="Returns an XYZ of -1,0,0" Category="Clockwork.Geometry.Vector.Create">
  <NamespaceResolutionMap>
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Output guid="736d6bae-7579-41a1-929b-c31f20703209" type="Dynamo.Nodes.Output" nickname="Output" x="343" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="-1,0,0" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.CodeBlockNodeModel guid="522b8cce-a6b0-468f-b59e-cb26d02a4580" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="0" y="4.21833333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="Vector.XAxis().Reverse();" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="522b8cce-a6b0-468f-b59e-cb26d02a4580" start_index="0" end="736d6bae-7579-41a1-929b-c31f20703209" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
</Workspace>