<Workspace Version="0.8.1.1693" X="30" Y="208.244330104923" zoom="1.47699757869249" Name="Vector.YAxisNegative" ID="b88792f7-0b64-420d-81ca-43a08eb57bb4" Description="Returns an XYZ of 0,-1,0" Category="Clockwork.Geometry.Vector.Create">
  <NamespaceResolutionMap>
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Output guid="4eadf7d8-0216-448d-98c7-271f48e71de7" type="Dynamo.Nodes.Output" nickname="Output" x="343" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="0,-1,0" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.CodeBlockNodeModel guid="84586e8e-4815-4baf-94ce-2d7f7aec40ca" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="0" y="4.21833333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="Vector.YAxis().Reverse();" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="84586e8e-4815-4baf-94ce-2d7f7aec40ca" start_index="0" end="4eadf7d8-0216-448d-98c7-271f48e71de7" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
</Workspace>