<Workspace Version="0.9.0.3067" X="0" Y="0" zoom="1" Name="WallLocationLine.FinishFaceExterior" Description="Returns the WallLocationLine option for FinishFaceExterior" ID="28126966-67ff-4b1f-ae5c-47993debcca6" Category="Clockwork.Revit.Elements.WallLocationLine.Query">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="62d3116a-955c-4458-bcda-49cd5a3cbf37" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" inputcount="0">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

OUT = WallLocationLine.FinishFaceExterior</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.Output guid="0d54dfa3-7ad6-4c80-959d-1c8429eac09f" type="Dynamo.Nodes.Output" nickname="Output" x="419" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="FinishFaceExterior" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Output guid="02fac28f-91de-4c20-a82d-a58dfb597d28" type="Dynamo.Nodes.Output" nickname="Output" x="454" y="73" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="int" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.CodeBlockNodeModel guid="a0d48427-5b26-4811-98c8-87fc8cd9d416" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="260" y="77.2183333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="2;" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="62d3116a-955c-4458-bcda-49cd5a3cbf37" start_index="0" end="0d54dfa3-7ad6-4c80-959d-1c8429eac09f" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="a0d48427-5b26-4811-98c8-87fc8cd9d416" start_index="0" end="02fac28f-91de-4c20-a82d-a58dfb597d28" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>