<Workspace Version="0.9.0.3067" X="253.7230828125" Y="252.659373836458" zoom="2.45244625" Name="WallLocationLine.WallCenterline" Description="Returns the WallLocationLine option for WallCenterLine" ID="c2866671-246c-4bb2-95b9-045860d07e67" Category="Clockwork.Revit.Elements.WallLocationLine.Query">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="62d3116a-955c-4458-bcda-49cd5a3cbf37" type="PythonNodeModels.PythonNode" nickname="Python Script" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" inputcount="0">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

OUT = WallLocationLine.WallCenterline</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.Output guid="0d54dfa3-7ad6-4c80-959d-1c8429eac09f" type="Dynamo.Nodes.Output" nickname="Output" x="194" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="WallCenterline" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.CodeBlockNodeModel guid="5a5e184d-a498-4dd1-876a-c8d367f00edb" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="0" y="88.2183333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="0;" ShouldFocus="false" />
    <Dynamo.Nodes.Output guid="b1829374-496c-4126-bd34-db0daa540186" type="Dynamo.Nodes.Output" nickname="Output" x="194" y="84" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="int" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="62d3116a-955c-4458-bcda-49cd5a3cbf37" start_index="0" end="0d54dfa3-7ad6-4c80-959d-1c8429eac09f" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="5a5e184d-a498-4dd1-876a-c8d367f00edb" start_index="0" end="b1829374-496c-4126-bd34-db0daa540186" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>