<Workspace Version="0.9.0.3067" X="35" Y="147.063333333333" zoom="4" Name="WallLocationLine.CoreCenterline" Description="Returns the WallLocationLine option for CoreCenterLine" ID="12fdf076-77a9-4aea-8fbf-80a584a5fbfa" Category="Clockwork.Revit.Elements.WallLocationLine.Query">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="62d3116a-955c-4458-bcda-49cd5a3cbf37" type="PythonNodeModels.PythonNode" nickname="Python Script" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" inputcount="0">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

OUT = WallLocationLine.CoreCenterline</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.Output guid="0d54dfa3-7ad6-4c80-959d-1c8429eac09f" type="Dynamo.Nodes.Output" nickname="Output" x="194" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="CoreCenterline" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Output guid="554b9b8c-328d-4907-8c01-2074e6f29f02" type="Dynamo.Nodes.Output" nickname="Output" x="194" y="84" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="int" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.CodeBlockNodeModel guid="58ad6a00-8e48-4f0a-82b2-5ae90b483891" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="0" y="88.2183333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="1;" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="62d3116a-955c-4458-bcda-49cd5a3cbf37" start_index="0" end="0d54dfa3-7ad6-4c80-959d-1c8429eac09f" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="58ad6a00-8e48-4f0a-82b2-5ae90b483891" start_index="0" end="554b9b8c-328d-4907-8c01-2074e6f29f02" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>