<Workspace Version="0.9.0.3067" X="0" Y="0" zoom="1" Name="WallLocationLine.FinishFaceInterior" Description="Returns the WallLocationLine option for FinishFaceInterior" ID="66a8de31-e6ac-4f05-9ead-93ac8372e358" Category="Clockwork.Revit.Elements.WallLocationLine.Query">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="62d3116a-955c-4458-bcda-49cd5a3cbf37" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" inputcount="0">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

OUT = WallLocationLine.FinishFaceInterior</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.Output guid="0d54dfa3-7ad6-4c80-959d-1c8429eac09f" type="Dynamo.Nodes.Output" nickname="Output" x="419" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="FinishFaceInterior" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Output guid="be646830-893e-4bab-ba88-cffe1b9c5e80" type="Dynamo.Nodes.Output" nickname="Output" x="423" y="65" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="int" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.CodeBlockNodeModel guid="62d588d4-18fa-49d6-a50e-3646bc0cd91d" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="229" y="69.2183333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="3;" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="62d3116a-955c-4458-bcda-49cd5a3cbf37" start_index="0" end="0d54dfa3-7ad6-4c80-959d-1c8429eac09f" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="62d588d4-18fa-49d6-a50e-3646bc0cd91d" start_index="0" end="be646830-893e-4bab-ba88-cffe1b9c5e80" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>