<Workspace Version="0.8.2.2392" X="30" Y="366.786078098472" zoom="1.21561969439728" Name="Document.StartingView" Description="Retrieves the starting view of a Project file. Returns null if no starting view is set." ID="a6f12732-38d4-4711-9497-a856f76b2dfe" Category="Clockwork.Revit.Document.Query">
  <NamespaceResolutionMap />
  <Elements>
    <DSIronPythonNode.PythonNode guid="39066300-9f69-4b51-bd5d-2d377f54c6c1" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="299" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
OUT = doc.GetElement(StartingViewSettings.GetStartingViewSettings(doc).ViewId)</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Output guid="7173ccbe-96d5-44b7-9875-51072fae3bfe" type="Dynamo.Nodes.Output" nickname="Output" x="523" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="view" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Symbol guid="086ca5b7-e31d-478b-8ee9-bf87161c2140" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="2.1316282072803E-14" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="toggle : bool = true" />
    </Dynamo.Nodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="39066300-9f69-4b51-bd5d-2d377f54c6c1" start_index="0" end="7173ccbe-96d5-44b7-9875-51072fae3bfe" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="086ca5b7-e31d-478b-8ee9-bf87161c2140" start_index="0" end="39066300-9f69-4b51-bd5d-2d377f54c6c1" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>