<Workspace Version="1.3.3.4651" X="263.837388015173" Y="58.6550181476467" zoom="0.642869557405948" ScaleFactor="1" Name="Collector of Printsettings" Description="Collects printsettings and their names in the active or given document.&#xD;&#xA;Inspired by archilab" ID="b37779eb-3acc-4a3b-a121-a7b38c7e38e5" Category="GeniusLoci.Printing">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="05dfe8e9-289c-4cf2-97fb-c43544c09652" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="367.544187801459" y="409.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e56b878f-4bf2-4544-a5b6-fe133233e14f" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="536" y="397.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Printsetting" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="60c40369-b39f-4bcb-9729-a594fe475973" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="545.6" y="484.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Printsetting's name" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1ed4d5a8-0b6e-4441-96fe-54a1be38bb13" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-284.719327438291" y="407.773208160826" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Use only if you want to query a linked model&#xD;&#xA;docOrRevitLinkInstance : var = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="7630cbee-ae99-4106-91f2-749a383d4443" type="PythonNodeModels.PythonNode" nickname="Printsettings" x="184.427168185161" y="413.995310224797" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2015, Konrad Sobon
# @arch_laboratory, http://archi-lab.net

import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

inputdoc = UnwrapElement(IN[0])

#Part of script from Clockwork
if inputdoc == None:
	doc = DocumentManager.Instance.CurrentDBDocument
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.RevitLinkInstance":
	doc = inputdoc.GetLinkDocument()
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.Document":
	doc = inputdoc
else: doc = None

ps = FilteredElementCollector(doc).OfClass(PrintSetting)

OUT = [i for i in ps],[i.Name for i in ps]</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="05dfe8e9-289c-4cf2-97fb-c43544c09652" start_index="0" end="e56b878f-4bf2-4544-a5b6-fe133233e14f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="05dfe8e9-289c-4cf2-97fb-c43544c09652" start_index="1" end="60c40369-b39f-4bcb-9729-a594fe475973" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1ed4d5a8-0b6e-4441-96fe-54a1be38bb13" start_index="0" end="7630cbee-ae99-4106-91f2-749a383d4443" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7630cbee-ae99-4106-91f2-749a383d4443" start_index="0" end="05dfe8e9-289c-4cf2-97fb-c43544c09652" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>