<Workspace Version="1.3.4.6666" X="168.854342578611" Y="-87.1772178083028" zoom="0.743483769730132" ScaleFactor="1" Name="Create Line Pattern" Description="Creates a new LinePatternElement.&#xD;&#xA;A line pattern is made of dashes, dots alternating with spaces. A space must end the sequence." ID="38333975-ba2d-4431-9779-6c1f6f579a1b" Category="GeniusLoci.Graphics">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3d42e4ee-c882-42ac-88f4-4376914eb923" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-77.6961070416344" y="240.232189373607" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Name:string[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="899d2345-ff3a-465c-a748-af5137aeb424" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="428.559214522713" y="326.314786245325" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="LinePatternElement" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="58374bf1-6da2-4982-b9bd-b8a14dd45ca5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-77.6961070416344" y="323.232189373607" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Dash, Dot or Space&#xD;&#xA;types:string[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3ed875b5-5ec9-4385-9b2c-08ad78a3dcd2" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-79.699047796682" y="415.093973886369" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="LengthTypes:double[]..[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="1d351665-32bb-4a00-a454-da581c741567" type="PythonNodeModels.PythonNode" nickname="Python Script" x="243.930646808442" y="325.41074104143" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#Alban de Chasteigner 2018
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference('RevitNodes')
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit.DB import *

import sys
pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib'
sys.path.append(pyt_path)
import System

UIunit = Document.GetUnits(doc).GetFormatOptions(UnitType.UT_Length).DisplayUnits

patternName = IN[0]
types = IN[1]
values = IN[2]
lstSegments =  List[LinePatternSegment]()

for type,value in zip(types,values):
	if type == "Dash":
		lstSegments.Add(LinePatternSegment(LinePatternSegmentType.Dash,UnitUtils.ConvertToInternalUnits(value,UIunit)))
		
	elif type == "Space":
		lstSegments.Add(LinePatternSegment(LinePatternSegmentType.Space,UnitUtils.ConvertToInternalUnits(value,UIunit)))
	
	elif type == "Dot":
		lstSegments.Add(LinePatternSegment(LinePatternSegmentType.Dot,0))

linePattern = LinePattern(patternName)
linePattern.SetSegments(lstSegments)

#Create a linepattern element
TransactionManager.Instance.EnsureInTransaction(doc)
linePatternElement = LinePatternElement.Create(doc, linePattern)
TransactionManager.Instance.TransactionTaskDone()
OUT=linePatternElement</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="3d42e4ee-c882-42ac-88f4-4376914eb923" start_index="0" end="1d351665-32bb-4a00-a454-da581c741567" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="58374bf1-6da2-4982-b9bd-b8a14dd45ca5" start_index="0" end="1d351665-32bb-4a00-a454-da581c741567" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3ed875b5-5ec9-4385-9b2c-08ad78a3dcd2" start_index="0" end="1d351665-32bb-4a00-a454-da581c741567" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1d351665-32bb-4a00-a454-da581c741567" start_index="0" end="899d2345-ff3a-465c-a748-af5137aeb424" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>