<Workspace Version="1.3.3.4651" X="84.735" Y="72.891" zoom="0.8425" ScaleFactor="1" Name="Material Change Texture Path" Description="Works only in Revit 2018.1 and later.&#xD;&#xA;The material must already have an assigned texture." ID="4bd02371-a62f-4863-b968-3e8d758d9240" Category="GeniusLoci.Material">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="887e2c26-1b60-4536-b77f-d0ade403c9eb" type="PythonNodeModels.PythonNode" nickname="Change picture" x="359.6" y="218.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Inspired by Boris Shafiro from Autodesk
#Alban de Chasteigner 2018
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

def toList(obj):
    if hasattr(obj, '__iter__'): return obj
    else: return [obj]
    
mats = toList(UnwrapElement(IN[0]))
paths = toList(IN[1])

for mat, path in zip(mats, paths):
	appearanceAssetId = mat.AppearanceAssetId
	assetElem = doc.GetElement(appearanceAssetId)
	TransactionManager.Instance.EnsureInTransaction(doc)
	with Visual.AppearanceAssetEditScope(assetElem.Document) as editScope:
		editableAsset = editScope.Start(assetElem.Id)
		genericDiffuseProperty = editableAsset.FindByName("generic_diffuse")
		connectedAsset = genericDiffuseProperty.GetSingleConnectedAsset()
		bitmapProperty = connectedAsset["unifiedbitmap_Bitmap"]
		bitmapProperty.Value = path
		editScope.Commit(True)
	TransactionManager.Instance.TransactionTaskDone()

OUT = mats</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="80bf08a7-e78e-4ae9-9d63-b00115a4549f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="210.8" y="203.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Material" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="0f53346b-583f-40bc-8cf4-1e049efb2d0c" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="539.219268346913" y="216.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Material" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a050e1e0-0adb-4eed-bbf9-fff99e47bf15" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="186" y="298" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="FilePath" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="887e2c26-1b60-4536-b77f-d0ade403c9eb" start_index="0" end="0f53346b-583f-40bc-8cf4-1e049efb2d0c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="80bf08a7-e78e-4ae9-9d63-b00115a4549f" start_index="0" end="887e2c26-1b60-4536-b77f-d0ade403c9eb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a050e1e0-0adb-4eed-bbf9-fff99e47bf15" start_index="0" end="887e2c26-1b60-4536-b77f-d0ade403c9eb" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>