<Workspace Version="1.3.3.4651" X="274.938405911534" Y="-112.209433164551" zoom="1.04226481803878" ScaleFactor="1" Name="SelectByCategoryAndHost3DView" Description="Collects elements in the given document by category and in the host 3D view of the active document.&#xD;&#xA;The transform CS is returned only with a LinkInstance input." ID="45627d39-aee2-479b-8d50-29c7e20c4c35" Category="GeniusLoci.Select">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="21e0513d-21c2-497a-8d31-8f7072034275" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="64.0537716011251" y="203.957886747973" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//View of active document&#xD;&#xA;ThreeDView" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="baaf42c0-c9a1-4592-89cd-18ea5c4fa65d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="177.656920426882" y="295.286731013561" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Category" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="473a671d-61ed-4250-977d-c9165397ddf1" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-125.349498167852" y="374.108684393824" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Use only if you want to query a linked model&#xD;&#xA;docOrRevitLinkInstance : var[] = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="cd8c4e7c-bb21-4048-b526-5df7c11b9ffe" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="613.679727807558" y="244.580068048111" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="aa97dc3a-3425-4dbc-ac48-4c1b11387ec1" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="783.856291915432" y="230.506363454351" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="942d47bf-09ae-480a-be5f-38526384f021" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="782.733634321847" y="295.620503882296" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Transform" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="46b4fa76-c07f-45bc-bf14-509d40395001" type="PythonNodeModels.PythonNode" nickname="SelectByCategoryAnd3DView" x="362.340102609619" y="245.142649256415" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#Inspired by Einar_Raknes
#Alban de Chasteigner 2018
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference('RevitAPI')
clr.AddReference('System')
clr.AddReference('RevitNodes')
clr.AddReference('RevitServices')
import Revit
import RevitServices
from Autodesk.Revit.DB import *
from System.Collections.Generic import List
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

def tolist(x):
    if hasattr(x,'__iter__'): return x
    else : return [x]

views = tolist(UnwrapElement(IN[0]))
cats = tolist(UnwrapElement(IN[1]))
inputdocs = tolist(UnwrapElement(IN[2]))
transforms = []

for inputdoc in inputdocs :
	if inputdoc == None:
		doc = DocumentManager.Instance.CurrentDBDocument
	elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.Document":
		doc = inputdoc
	elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.RevitLinkInstance":
		doc = inputdoc.GetLinkDocument()
		transforms.append(inputdoc.GetTotalTransform().ToCoordinateSystem(1))
	else: 
		transforms.append(None)

viewlist = []

for view in views:
    viewlist.append(view)
    sectionbox = view.GetSectionBox()
    transform = sectionbox.Transform
    sboxoriginx = transform.Origin.X
    sboxoriginy = transform.Origin.Y
    sboxoriginz = transform.Origin.Z
    minx = sectionbox.Min.X + sboxoriginx
    maxx = sectionbox.Max.X + sboxoriginx
    miny = sectionbox.Min.Y + sboxoriginy
    maxy = sectionbox.Max.Y + sboxoriginy
    minz = sectionbox.Min.Z + sboxoriginz
    maxz = sectionbox.Max.Z + sboxoriginz
    bbox = BoundingBoxXYZ()

catlist = []
linkedEl = []
elements = []

for cat in cats:
	catlist.append(cat.Id)
filtercats = List[ElementId](catlist)
catfilter = ElementMulticategoryFilter(filtercats)
	
outline = Outline(XYZ((minx), (miny), (minz)), XYZ((maxx), (maxy), (maxz)))
bbfilter = BoundingBoxIntersectsFilter(outline)
andfilter = LogicalAndFilter(catfilter,bbfilter)

collector = FilteredElementCollector(doc).WherePasses(andfilter)
for col in collector:
	linkedEl.append(col.ToDSType(True))
elements.append(linkedEl)

OUT = elements[0],transforms</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="21e0513d-21c2-497a-8d31-8f7072034275" start_index="0" end="46b4fa76-c07f-45bc-bf14-509d40395001" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="baaf42c0-c9a1-4592-89cd-18ea5c4fa65d" start_index="0" end="46b4fa76-c07f-45bc-bf14-509d40395001" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="473a671d-61ed-4250-977d-c9165397ddf1" start_index="0" end="46b4fa76-c07f-45bc-bf14-509d40395001" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cd8c4e7c-bb21-4048-b526-5df7c11b9ffe" start_index="0" end="aa97dc3a-3425-4dbc-ac48-4c1b11387ec1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cd8c4e7c-bb21-4048-b526-5df7c11b9ffe" start_index="1" end="942d47bf-09ae-480a-be5f-38526384f021" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="46b4fa76-c07f-45bc-bf14-509d40395001" start_index="0" end="cd8c4e7c-bb21-4048-b526-5df7c11b9ffe" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Aperçu en arrière-plan" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>