<Workspace Version="1.3.3.4651" X="-65.967533434824" Y="150.537798838591" zoom="0.60498987240461" ScaleFactor="1" Name="SelectByCategoryAndDesignOption" Description="Select all elements by Design Option and category in the given document.&#xD;&#xA;From archilab" ID="618cce60-90e3-4ad3-9bea-ed326d75e583" Category="GeniusLoci.Select">
  <NamespaceResolutionMap>
    <ClassMap partialName="DSCore.List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f4ca5337-e496-49de-9c26-c70395f9e11e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="651.958633129024" y="302.432937879402" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Category" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="4047199f-b52b-4e06-9518-09c6cef00a8c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="295.105510902371" y="209.534788435583" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Collected DesignOption in active or linked document&#xD;&#xA;DesignOption" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="73be5532-513e-4a21-9a1b-54459e7fd3cf" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1088.48725377166" y="260.657498362262" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="b7e3d0cd-a7db-4707-9c39-7d0712cdbe08" type="PythonNodeModels.PythonNode" nickname="SelectByCategoryAndDesign" x="858.761768301224" y="257.595802228006" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#Copyright(c) 2014, Konrad K Sobon
# Grimshaw Architects, http://grimshaw-architects.com/
# Archi-lab, http://wwww.archi-lab.net

# Default imports
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

#Import Collections
from System.Collections.Generic import *
import System

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

def tolist(x):
    if hasattr(x,'__iter__'): return x
    else : return [x]

designOptions = tolist(UnwrapElement(IN[0]))
cats = tolist(IN[1])
inputdocs = tolist(UnwrapElement(IN[2]))
catlist = []

#Part of script from Clockwork
for inputdoc in inputdocs :
	if inputdoc == None:
		doc = DocumentManager.Instance.CurrentDBDocument
	elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.Document":
		doc = inputdoc
	elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.RevitLinkInstance":
		doc = inputdoc.GetLinkDocument()
	else: doc = None

for cat in cats:
	bic = System.Enum.ToObject(BuiltInCategory, cat.Id)
	for designOption in designOptions:
		filterdesign = ElementDesignOptionFilter(designOption.Id)
		catlist.append(FilteredElementCollector(doc).WherePasses(filterdesign).OfCategory(bic).ToElements())		

OUT=catlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="46878d79-8253-49d2-b40a-11e0dfe3b812" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="328.189097438175" y="393.725514250026" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Use only if you want to query a linked model&#xD;&#xA;docOrRevitLinkInstance : var = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f4ca5337-e496-49de-9c26-c70395f9e11e" start_index="0" end="b7e3d0cd-a7db-4707-9c39-7d0712cdbe08" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4047199f-b52b-4e06-9518-09c6cef00a8c" start_index="0" end="b7e3d0cd-a7db-4707-9c39-7d0712cdbe08" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b7e3d0cd-a7db-4707-9c39-7d0712cdbe08" start_index="0" end="73be5532-513e-4a21-9a1b-54459e7fd3cf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="46878d79-8253-49d2-b40a-11e0dfe3b812" start_index="0" end="b7e3d0cd-a7db-4707-9c39-7d0712cdbe08" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>