<Workspace Version="1.3.3.4651" X="70.182" Y="60.48" zoom="0.8425" ScaleFactor="1" Name="SelectByCategoryAndBoundingBox" Description="Collect elements by category from a BoundingBox." ID="ac6acb90-e6c0-464e-959b-a1140ae284b0" Category="GeniusLoci.Select">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="2fd013f0-078c-4bb5-ae72-a9200d136f28" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="461.926546098665" y="229.335160673074" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a0e0cc2e-c2ab-4a9f-ac88-60b127bd2cda" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="13.806528189911" y="193.061127596439" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="BoundingBox" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="bfb47689-68f3-47ea-aa01-0855e11d047e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="33.5609674636496" y="264.295398061798" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Category" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <PythonNodeModels.PythonNode guid="153205fa-f3ed-463b-9125-26d8b501183d" type="PythonNodeModels.PythonNode" nickname="Python Script" x="249.991691394659" y="215.928783382789" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#From Einar_Raknes

import clr
clr.AddReference('RevitAPI')
clr.AddReference('System')
clr.AddReference('RevitNodes')
clr.AddReference('RevitServices')
import Revit
import RevitServices
from Autodesk.Revit.DB import *
from System.Collections.Generic import List
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)
doc = DocumentManager.Instance.CurrentDBDocument

#Functions for list handling
def ProcessList(_func, _list):
   return map( lambda x: ProcessList(_func, x) if type(x)==list else _func(x), _list )

#Preparing input from dynamo to revit

def ToRevit(item):
	return item.ToRevitType(True)

if isinstance(IN[0], list):
	bblist = ProcessList(ToRevit, IN[0])
else:
	bblist = [ToRevit(IN[0])]

if isinstance(IN[1], list):
	cats = ProcessList(UnwrapElement, IN[1])
else:
	cats = [UnwrapElement(IN[1])]

catlist = []
for cat in cats:
	catlist.append(cat.Id)
filtercats = List[ElementId](catlist)
catfilter = ElementMulticategoryFilter(filtercats)

def collectElementsInBB(bb):
	outline = Outline(bb.Min, bb.Max)
	bbfilter = BoundingBoxIntersectsFilter(outline)
	andfilter = LogicalAndFilter(catfilter,bbfilter)
	collector = FilteredElementCollector(doc).WherePasses(andfilter)
	return [e.ToDSType(True) for e in collector]

OUT = ProcessList(collectElementsInBB, bblist)[0]</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="a0e0cc2e-c2ab-4a9f-ac88-60b127bd2cda" start_index="0" end="153205fa-f3ed-463b-9125-26d8b501183d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bfb47689-68f3-47ea-aa01-0855e11d047e" start_index="0" end="153205fa-f3ed-463b-9125-26d8b501183d" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="153205fa-f3ed-463b-9125-26d8b501183d" start_index="0" end="2fd013f0-078c-4bb5-ae72-a9200d136f28" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>