<Workspace Version="1.2.1.3083" X="-1812.93787179323" Y="665.234628912583" zoom="1.99980151612264" Name="Group.UngroupElements" Description="This will ungroup the input groups and output their elements. Use with care!" ID="fb0642a6-3b48-46a8-bd96-706a28539580" Category="Rhythm.Revit.Elements.Group">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="0af60033-ffb1-400f-b399-a22eaf6a3ba7" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1198.56347366768" y="-196.778833796991" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Created by DPS Design, dpsdesign.org
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

from System.Collections.Generic import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

#The inputs to this node will be stored as a list in the IN variable.
dataEnteringNode = IN

#unwrap all elements to use with API
items = UnwrapElement(IN[0])
TransactionManager.Instance.EnsureInTransaction(doc)
#apply lineweight override to elements in an input list
typelist = list()
for i in items:
	try:
		typelist.append(i.UngroupMembers())
	except:
		typelist.append(list())


# "End" the transaction
TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable
OUT = typelist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="73e98317-6ca2-40e8-8ed7-98550ceb3ad7" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="958.058231389046" y="-194.417903548646" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="f2556a2c-a2f8-4cd5-95b1-d44a8c056080" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1204.51605247643" y="-32.8903330440123" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
groups = UnwrapElement(IN[0])
elementlist = list()
for item in groups:
	try:
		memberlist = list()
		for member in item.GetMemberIds():
			memberlist.append(doc.GetElement(member))
		elementlist.append(memberlist)
	except:
		elementlist.append(list())
OUT = elementlist</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="425b3e95-9eee-4c93-9b4d-4b645d4839e3" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="844.052701323043" y="-180.135191421913" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="groups" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="89bcefb0-9b75-4472-99c6-c95e6c383dd1" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1419.60982072739" y="-190.636233565694" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="element" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="73e98317-6ca2-40e8-8ed7-98550ceb3ad7" start_index="0" end="0af60033-ffb1-400f-b399-a22eaf6a3ba7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="73e98317-6ca2-40e8-8ed7-98550ceb3ad7" start_index="0" end="f2556a2c-a2f8-4cd5-95b1-d44a8c056080" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f2556a2c-a2f8-4cd5-95b1-d44a8c056080" start_index="0" end="89bcefb0-9b75-4472-99c6-c95e6c383dd1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="425b3e95-9eee-4c93-9b4d-4b645d4839e3" start_index="0" end="73e98317-6ca2-40e8-8ed7-98550ceb3ad7" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="1ba08407-0905-4c47-bc6c-a610ef267c9f" annotationText="Thanks to Andreas for this script&#xD;&#xA;Download clockwork for more" left="1194.51605247643" top="-110.090333044012" width="142.4" height="145" fontSize="14" InitialTop="-32.8903330440123" InitialHeight="98" TextblockHeight="67.2" backgrouund="#FFC1D676">
      <Models ModelGuid="f2556a2c-a2f8-4cd5-95b1-d44a8c056080" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>