<Workspace Version="1.1.0.2094" X="258.691772464106" Y="150.348126900688" zoom="0.889203022025033" Name="Springs.CurveLoop.Simplify" Description="Attempts to simplify an open or a closed curve loop by connecting straight separate line segments into a single line." ID="b255f316-935c-41a1-abe7-386417b84b6f" Category="Springs.Geometry">
  <NamespaceResolutionMap>
    <ClassMap partialName="Cuboid" resolvedName="Autodesk.DesignScript.Geometry.Cuboid" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="NurbsCurve" resolvedName="Autodesk.DesignScript.Geometry.NurbsCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Rectangle" resolvedName="Autodesk.DesignScript.Geometry.Rectangle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="7c14cbfb-dca8-4824-b7fb-1dde6aa201bb" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="410.666343054725" y="9.89109394496766" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="merge1(lines);" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="fc000ed1-173a-4d0f-98c0-e661694f10ed" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="244.128219142628" y="76.3684206975544" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="def cPts(c1){&#xA;return = {c1.StartPoint,c1.EndPoint};&#xA;};&#xA;&#xA;def isLine(c1){&#xA;return = Math.Abs(c1.Length - Line.ByBestFitThroughPoints&#xA;	(cPts(c1) ).Length) &lt;= 0.0001;&#xA;};&#xA;&#xA;def cVec(c1){&#xA;pts = cPts(c1);&#xA;return = Vector.ByTwoPoints(pts[0], pts[1]);&#xA;};&#xA;&#xA;def merge1(lines:var[]){&#xA;return = [Imperative]{&#xA;lines = PolyCurve.ByJoinedCurves(lines).Curves();&#xA;lines = List.AddItemToEnd(lines[0], lines);&#xA;i = 0;&#xA;out1 = {};&#xA;while (i &lt; Count(lines) -1)&#xA;{&#xA;	pts = cPts(lines[i]);&#xA;	while (isLine(lines[i+1]) &amp;&amp; cVec(lines[i])&#xA;		.AngleWithVector(cVec(lines[i+1])) &lt; 0.0001)&#xA;	{&#xA;		pts = List.Join({pts, cPts(lines[i+1])});&#xA;		i = i + 1;&#xA;	}&#xA;	if (Count(pts) == 2)&#xA;	{&#xA;		out1 = List.Join({out1,lines[i]});&#xA;		i = i + 1;&#xA;	}&#xA;	else&#xA;	{&#xA;		out1 = List.Join({out1,Line.&#xA;			ByBestFitThroughPoints(pts)});&#xA;		i = i + 1;&#xA;	}&#xA;}&#xA;if (out1[-1].Intersect(out1[0])[0].Length != null)&#xA;	{&#xA;		out1 = List.RestOfItems(out1);&#xA;	}&#xA;return = out1;&#xA;}};" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="cc212e84-7ffb-4951-a0c1-d3539e102f8d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="232.579068038483" y="8.41510865672046" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="curveLoop: var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="72be7d9a-98cb-4ec0-a420-86265389c8a8" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="613.1981084343" y="7.42364947644782" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="curve loop" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7c14cbfb-dca8-4824-b7fb-1dde6aa201bb" start_index="0" end="72be7d9a-98cb-4ec0-a420-86265389c8a8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cc212e84-7ffb-4951-a0c1-d3539e102f8d" start_index="0" end="7c14cbfb-dca8-4824-b7fb-1dde6aa201bb" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="110.594947814941" eyeY="205.909820556641" eyeZ="-176.049072265625" lookX="-6.42372941970825" lookY="-238.832733154297" lookZ="64.4785232543945" upX="0.0990167707204819" upY="-0.0488497689366341" upZ="-0.99388599395752" />
  </Cameras>
</Workspace>