<Workspace Version="0.7.1.29946" X="-79" Y="154" zoom="1.1" Description="Converts a point string &quot;x,y,z&quot; into a true Point." Category="LunchBox.Archive.Format" Name="LunchBox String to Point" ID="02f21938-a837-4030-9346-cb3aae489e7f">
  <Elements>
    <DSIronPythonNode.PythonNode type="DSIronPythonNode.PythonNode" guid="b46b21a7-aad3-4839-8c63-3b3198ab7948" nickname="Python Script" x="489.58361083361" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="1">
      <Script>#Copyright(c) 2014, Nathan Miller
# The Proving Ground, http://theprovingground.org

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

#The input to this node will be stored in the IN[0] variable.
ptslist = IN[0]

ptsarr = []

#if the input is an array
if hasattr(ptslist, "__iter__"):

	#if the input is a nested array
	if hasattr(ptslist[0], "__iter__"):
		for i in range(0, len(ptslist)):
			ptstr = ptslist[i]
			pts = []
			for j in range(0,len(ptstr)):
				str = ptstr[j]
				strarr = str.Split(",")
				x = float(strarr[0])
				y = float(strarr[1])
				z = float(strarr[2])
				pt = Point.ByCoordinates(x,y,z)
				pts.append(pt)
			ptsarr.append(pts)
	else:
		for i in range(0,len(ptslist)):
		
			#split string
			str = ptslist[i]
			strarr = str.Split(",")
	
			#compose points
			x = float(strarr[0])
			y = float(strarr[1])
			z = float(strarr[2])
			pt = Point.ByCoordinates(x,y,z)
			ptsarr.append(pt)
else:
	#split string
	str = ptslist
	strarr = str.Split(",")
	x = float(strarr[0])
	y = float(strarr[1])
	z = float(strarr[2])
	pt = Point.ByCoordinates(x,y,z)
	ptsarr.append(pt)

#Assign your output to the OUT variable
OUT = ptsarr</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="ceb3f037-3e22-43ef-b0b1-e51a463da6ac" nickname="Input" x="339.090909090909" y="3.63636363636365" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="String" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="3c3960fd-340a-4054-822a-11468cefef22" nickname="Output" x="639.674519924519" y="-2.72727272727272" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="Point" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="b46b21a7-aad3-4839-8c63-3b3198ab7948" start_index="0" end="3c3960fd-340a-4054-822a-11468cefef22" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ceb3f037-3e22-43ef-b0b1-e51a463da6ac" start_index="0" end="b46b21a7-aad3-4839-8c63-3b3198ab7948" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>