<Workspace Version="1.3.3.4651" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Get Project Locations" Description="Works only in Revit 2018 and later.&#xD;&#xA;Retrieves the project positions with the survey point as the origin. &#xD;&#xA;(Coordinates of Internal origin, project base point and survey point)" ID="014d8b59-53b9-41aa-b9b2-b962cbebc311" Category="GeniusLoci.Document">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f0365078-e546-4b44-be6d-e86ce817203e" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="276.8" y="364.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Use only if you want to query a linked model&#xD;&#xA;docOrRevitLinkInstance : var = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="99a95d78-781b-4004-8d07-1e2893597bb6" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1212.8" y="336.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Active Project Location" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="6a8efd51-e638-45a6-846e-8efb8c62c869" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1215.6" y="411.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Project Base Point" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="4d2931a6-d55b-4ef1-9d4a-ec2e38eab203" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1224.8" y="494.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Project Survey Point" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="36875564-14a7-4703-8366-99e3f851e7ac" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1089" y="377" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];&#xA;x[1];&#xA;x[2];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="8a55f24f-b264-4358-9680-0e5e63345cca" type="PythonNodeModels.PythonNode" nickname="Get Project Origin, BasePoint and SurveyPoint" x="755.6" y="368.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
import math
# import Document Manager
clr.AddReference("RevitServices")
import RevitServices 
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
import Autodesk

#Part of script from Clockwork
inputdoc = UnwrapElement(IN[0])
if inputdoc == None:
	doc = DocumentManager.Instance.CurrentDBDocument
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.RevitLinkInstance":
	doc = inputdoc.GetLinkDocument()
elif inputdoc.GetType().ToString() == "Autodesk.Revit.DB.Document":
	doc = inputdoc
else: doc = None

UIunit = Document.GetUnits(doc).GetFormatOptions(UnitType.UT_Length).DisplayUnits

outProjBasePt= []
outProjSurvPt = []
outProjLoc= []

pbp = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_ProjectBasePoint).ToElements()
sbp = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_SharedBasePoint).ToElements()

pbpEW = Autodesk.Revit.DB.UnitUtils.ConvertFromInternalUnits(pbp[0].get_Parameter(BuiltInParameter.BASEPOINT_EASTWEST_PARAM).AsDouble(),UIunit)
pbpNS = Autodesk.Revit.DB.UnitUtils.ConvertFromInternalUnits(pbp[0].get_Parameter(BuiltInParameter.BASEPOINT_NORTHSOUTH_PARAM).AsDouble(),UIunit)
pbpElev = Autodesk.Revit.DB.UnitUtils.ConvertFromInternalUnits(pbp[0].get_Parameter(BuiltInParameter.BASEPOINT_ELEVATION_PARAM).AsDouble(),UIunit)
pbpAngle = pbp[0].get_Parameter(BuiltInParameter.BASEPOINT_ANGLETON_PARAM).AsDouble()*180/math.pi    
# Create Point from Project Base Point Values...
outProjBasePt.append(round(pbpEW,6))
outProjBasePt.append(round(pbpNS,6))
outProjBasePt.append(round(pbpElev,6))
outProjBasePt.append(round(pbpAngle,6))

pspEW = Autodesk.Revit.DB.UnitUtils.ConvertFromInternalUnits(sbp[0].get_Parameter(BuiltInParameter.BASEPOINT_EASTWEST_PARAM).AsDouble(),UIunit)
pspNS = Autodesk.Revit.DB.UnitUtils.ConvertFromInternalUnits(sbp[0].get_Parameter(BuiltInParameter.BASEPOINT_NORTHSOUTH_PARAM).AsDouble(),UIunit)
pspElev = Autodesk.Revit.DB.UnitUtils.ConvertFromInternalUnits(sbp[0].get_Parameter(BuiltInParameter.BASEPOINT_ELEVATION_PARAM).AsDouble(),UIunit)
outProjSurvPt.append(round(pspEW,6))
outProjSurvPt.append(round(pspNS,6))
outProjSurvPt.append(round(pspElev,6))
	    	
projPos = doc.ActiveProjectLocation.GetProjectPosition(XYZ(0,0,0))

if projPos == None:
	outProjLoc.append("No Project Position at origin point")
else:
	outProjLoc.append(round(Autodesk.Revit.DB.UnitUtils.ConvertFromInternalUnits(projPos.EastWest,UIunit),6))
	outProjLoc.append(round(Autodesk.Revit.DB.UnitUtils.ConvertFromInternalUnits(projPos.NorthSouth,UIunit),6))
     
OUT = [outProjLoc, outProjBasePt, outProjSurvPt]</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f0365078-e546-4b44-be6d-e86ce817203e" start_index="0" end="8a55f24f-b264-4358-9680-0e5e63345cca" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="36875564-14a7-4703-8366-99e3f851e7ac" start_index="0" end="99a95d78-781b-4004-8d07-1e2893597bb6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="36875564-14a7-4703-8366-99e3f851e7ac" start_index="1" end="6a8efd51-e638-45a6-846e-8efb8c62c869" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="36875564-14a7-4703-8366-99e3f851e7ac" start_index="2" end="4d2931a6-d55b-4ef1-9d4a-ec2e38eab203" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8a55f24f-b264-4358-9680-0e5e63345cca" start_index="0" end="36875564-14a7-4703-8366-99e3f851e7ac" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>