<Workspace Version="1.3.3.4651" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Material Set Render Appearance Color" Description="Works only in Revit 2018.1 and later.&#xD;&#xA;Copies the value of the graphic color into the rendering color of the Appearance Asset Element." ID="915fb823-a77f-4b3e-8759-acbb61cb8ef4" Category="GeniusLoci.Material">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="041ec430-0bd8-40f3-9e99-3f5eadc2b545" type="PythonNodeModels.PythonNode" nickname="Set Appearance Color" x="441.6" y="190.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Inspired by Boris Shafiro from Autodesk
#Alban de Chasteigner 2018
#twitter : @geniusloci_bim
#geniusloci.bim@gmail.com

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

def tolist(obj):
    if hasattr(obj, '__iter__'): return obj
    else: return [obj]

materials = tolist(UnwrapElement(IN[0]))

for mat in materials :
	appearanceAssetId = mat.AppearanceAssetId
	assetElem = doc.GetElement(appearanceAssetId)
	TransactionManager.Instance.EnsureInTransaction(doc)
	with Visual.AppearanceAssetEditScope(assetElem.Document) as editScope:
		editableAsset = editScope.Start(assetElem.Id)
		genericDiffuseProperty = editableAsset.FindByName("generic_diffuse")
		genericDiffuseProperty.SetValueAsColor(mat.Color)
		editScope.Commit(True)
	TransactionManager.Instance.TransactionTaskDone()

OUT = materials</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="bff44ee4-987e-429c-be40-5a461f19c40f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="309.2" y="189.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Material" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="12316c9d-8449-43ee-a09f-a3a82e652bea" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="619.6" y="191.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Material" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="041ec430-0bd8-40f3-9e99-3f5eadc2b545" start_index="0" end="12316c9d-8449-43ee-a09f-a3a82e652bea" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bff44ee4-987e-429c-be40-5a461f19c40f" start_index="0" end="041ec430-0bd8-40f3-9e99-3f5eadc2b545" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>